### ISSUE TITLE
Unable to use Select-MgProfile to change profile in BeforeAll block

### ISSUE THREAD

**Issue by salbeck-sit** [pester/Pester#2256] opened 2022-11-10 13:39 UTC
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

I'm attempting to create tests for functions that calls Microsoft Graph beta-cmdlets that don't exist in the v1.0 profile, so in the functions, I use Select-MgProfile. However, the mocks of the cmdlets are placed in an InModuleScope->BeforeAll block and I need to be able to select the correct profile there.
I could do it prior to calling Invoke-Pester (tested and works fine) but as I run tests along with other functions that use the v1.0 profile, that wouldn't be nice to them.

### Expected Behavior

After this call: Select-MgProfile -Name beta
Then this call should return 'Name:beta': Get-MgProfile
But - it returns v1.0 as if Select-MgProfile hadn't been called or the result from the call didn't persist

### Steps To Reproduce

```powershell
Describe ... {
    InModuleScope .... ScriptBlock {
        BeforeAll {  # can also be placed before Describe - same issue
                write-host "Before: $((Get-MgProfile).Name)"
                Select-MgProfile -Name Beta -ErrorAction Stop
                write-host "After:  $((Get-MgProfile).Name)"
               # (...)
        }
        Context -Name {
            (...)
        }
    }
}            
```

### Describe your environment

Pester version     : 5.3.3 C:\Program Files\WindowsPowerShell\Modules\Pester\5.3.3\Pester.psm1
PowerShell version : 5.1.14393.5127
OS version         : Microsoft Windows NT 10.0.14393.0

**Comment by fflaten** [comment] 2022-11-10 16:39
To future self or others:
Looks like the profile is stored in a string property in a singleton in the same binary Authentication-module as the cmdlets. 

`GraphSession.Instance.SelectedProfile`

**Comment by fflaten** [comment] 2022-11-27 13:07
Thanks for the report, but I can't reproduce it. Tested on Windows PowerShell 5.1 and PS 7.3 (windows and ubuntu). The selected profile is persisted as a global setting, so not bound to module state neither.

```ps1
# SelectMgProfile.tests.ps1

BeforeDiscovery {
    Get-Module 'demoModule' | Remove-Module
    New-Module 'demoModule' { } | Import-Module
}

Describe abc {
    InModuleScope 'demoModule' {
        BeforeAll {
            Write-Host "In ModuleState? $($ExecutionContext.SessionState.Module.Name)"
            Write-Host "Before: $((Get-MgProfile).Name)"
            Select-MgProfile -Name Beta -ErrorAction Stop
            Write-Host "After:  $((Get-MgProfile).Name)"
        }
        It 'i' {
            Write-Host "In It:  $((Get-MgProfile).Name)"
            1 | Should -Be 1
        }
    }

    AfterAll {
        Write-Host "In ModuleState? $($ExecutionContext.SessionState.Module.Name)"
        Write-Host "AfterAll: $((Get-MgProfile).Name)"
        Select-MgProfile -Name v1.0
        Write-Host "AfterAll Reverted:  $((Get-MgProfile).Name)"
    }
}
```

```console
Pester v5.3.3

Starting discovery in 1 files.
Discovery found 1 tests in 9ms.
Running tests.

Running tests from 'C:\git\pester\samples\SelectMgProfile.tests.ps1'
In ModuleState? demoModule
Before: v1.0
After:  beta
Describing abc
In It:  beta
  [+] i 4ms (2ms|2ms)
In ModuleState?
AfterAll: beta
AfterAll Reverted:  v1.0
Tests completed in 52ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

Closing for now but can revisit if you're able to provide a complete sample for repro.

**Closed by fflaten** 2022-11-27 13:07 UTC
