### ISSUE TITLE
Add parameter to Invoke-Pester to run one or more It blocks

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#461] opened 2016-01-25 21:24 UTC
Some of our test fixture have many "It" blocks and each one can take a long time. Invoke-Pester has a `-TestName` parameter, but that is used to run all the `It` blocks in a specific `Describe` block. (Which surprised me. I expected `-TestName` to run a specific `It` block.)

Please add a parameter (`It`?) that will run one or more specific It blocks. If we can decide on a name for the parameter, I'd be happy to submit a pull request for it.

**Comment by dlwyatt** [comment] 2016-01-25 22:58
I don't know of a good way for us to implement that at this time.  Pester doesn't even know that your It blocks exist until it has already executed the parent Describe / Context blocks, and that's where most of your execution time tends to be anyway.

If we assume that all of the test code is in a single file (no dot-sourcing other scripts, calling Pester functions from there, etc), then we could maybe use the AST to parse the tests file ahead of time and figure out which test groups to execute in order to hit the proper children.  Two problems with that, though:  We still support PowerShell v2 (which has AST), and I know that quite a few projects out there _do_ split their test code across multiple files.

**Comment by nohwnd** [comment] 2016-01-26 08:52
This would be simple to implement if we could force test authors to put code in `It` only. The Describe would be used only as grouping/setup/teardown construct. So code like this would fail, because there is addtional code outside of It:

```powershell
Describe "hello" {
    "abc" | Set-Content C:\temp\testfile1.txt 
     It "test content" {
         #...
     }
}
```
If we were able to do that, we could run every describe and inside of the `It` function we could check the current filter and either execute the script block of the current `It` or do nothing and continue to next `It`.

This is unfortunately not possible because Describe, Context and It are just a plain PowerShell functions.  And so you can scatter code all over the place (and lot of people actually do that), and so running every Describe would execute all the actions that are placed outside of `It`.

**Comment by dlwyatt** [comment] 2016-01-26 12:36
It would be pretty limiting to have to put all code inside an `It` block anyway.  I generally do all of the Arrange-Act stuff out in the Describe or Context, and then just put assertions inside the `It`.  (In many cases, there are several `It` blocks associated with whatever arrange/act code just ran.

**Comment by nohwnd** [comment] 2016-01-26 17:34
reusing SUT between tests may make your tests depend on each other. I tend to recrrate SUT for every It so I don't need to place code in Describe. But that's just academical discussion, which does not change the fact that there is no good way to run It blocks only.

**Comment by splatteredbits** [comment] 2016-01-28 19:57
Can't we do something similar to what happens in Describe? It reaches out to a global $Pester object to figure out what test to filter out. Can It do the same thing, e.g.

    if ($null -eq (& $SafeCommands['Get-Variable'] -Name Pester -ValueOnly -ErrorAction $script:IgnoreErrorPreference))
    {
        # User has executed a test script directly instead of calling Invoke-Pester
        $Pester = New-PesterState -Path (& $SafeCommands['Resolve-Path'] .) -ItNameFilter $null -SessionState $PSCmdlet.SessionState
    }

    if($Pester.ItNameFilter -and -not ($Pester.ItNameFilter | & $SafeCommands['Where-Object'] { $name -like $_ }))
    {
        #skip this It block
        return
    }

**Comment by dlwyatt** [comment] 2016-01-28 20:05
I've considered something like that before, but the problem is that you have to execute all of the Describe / Context blocks to even get that far, and the It blocks themselves don't tend to add much more in the way of execution time.

**Comment by dlwyatt** [comment] 2016-02-02 03:31
I think I'm going to go ahead and do this in v4.0, since it meshes well with another change I'm working on anyway.  However, it will have the two limitations I mentioned earlier:  won't work on PowerShell v2 (old behavior applies there), and won't work if the pester functions are called from a separate file than the *.Tests.ps1 file that's being parsed (sorry, Microsoft.)

**Comment by nohwnd** [comment] 2019-03-24 11:58
I am closing this because it is partially duplicate of #721 and it's part of v5 design.

**Closed by nohwnd** 2019-03-24 11:58 UTC
Labels: Question
