### ISSUE TITLE
Problem mocking Test-Connection

### ISSUE THREAD

**Issue by mrboring** [pester/Pester#1295] opened 2019-04-24 11:30 UTC
## 1. General summary of the issue

Mocking Test-Connection results in an error referring to `GetParamBlock`.

### Sample code

```powershell
function DoSomething {
    Test-Connection -TargetName 'dummyTarget' -TCPPort 25 -Quiet
}

Describe -Name 'DoSomething' -Fixture {
    It -Name 'Mocking Test-Connection should return $true' -Test {
        Mock -CommandName 'Test-Connection' -MockWith {return $true}

        $result = DoSomething

        $result | Should -BeTrue

        Assert-MockCalled -CommandName 'Test-Connection' -Scope It -Exactly 1
    }
}
```

## 2. Describe Your Environment

```powershell
Pester version     : 4.7.3 C:\Users\<REMOVED>\Documents\PowerShell\Modules\Pester\4.7.3\Pester.psd1
PowerShell version : 6.2.0
OS version         : Microsoft Windows NT 10.0.17763.0

Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## 3. Expected Behavior

I expected the test to pass.

### Output of running `Invoke-Pester .\Untitled.tests.ps1`

```powershell
Executing all tests in '.\Untitled.tests.ps1'

Executing script .\Untitled.tests.ps1

  Describing DoSomething
    [-] Mocking Test-Connection should return $true 7ms
      NullReferenceException: Object reference not set to an instance of an object.
      MethodInvocationException: Exception calling "GetParamBlock" with "1" argument(s): "Object reference not set to an instance of an object."
      at Mock, C:\Users\<REMOVED>\Documents\PowerShell\Modules\Pester\4.7.3\Functions\Mock.ps1: line 237
      at <ScriptBlock>, C:\<REMOVED>\Untitled.tests.ps1: line 7
Tests completed in 58ms
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by renehernandez** [comment] 2019-04-24 13:08
@mrboring This is already a known issue with the PowerShell Core 6.2.0 release (https://github.com/PowerShell/PowerShell/issues/9058)

**Comment by mrboring** [comment] 2019-04-24 13:11
@renehernandez Thanks for the prompt, and helpful, reply!

**Comment by mikeclayton** [comment] 2019-04-29 08:47
Just to leave an audit trail, this is the same underlying issue as reported in https://github.com/pester/Pester/issues/1289 for ConvertFrom-Json:

**Comment by SQLDBAWithABeard** [comment] 2019-10-01 20:24
So the issue is resolved in PowerShell repo but I am still getting this using pwsh 6.2.3 - what am I missing?

**Comment by lboening** [comment] 2020-05-27 19:26
I rewrote the test a bit:

```powershell
function DoSomething {
    Test-netConnection -ComputerName 'dummyTarget' -Port 25
}

Describe -Name 'DoSomething' -Fixture {
    It -Name 'Mocking Test-Connection should return $true' -Test {
        Mock -CommandName 'Test-NetConnection' -MockWith {return $true}

        $result = DoSomething

        $result | Should -Be $true

        Assert-MockCalled -CommandName 'Test-NetConnection' -Scope It -Exactly 1
    }
}
```

This returned successfully.

I tried it on 5.1.17134.858.

**Closed** 2021-05-23 14:25 UTC
Labels: Bug - external to Pester
