### ISSUE TITLE
Troubleshooting Code Coverage

### ISSUE THREAD

**Issue by Glober777** [pester/Pester#2019] opened 2021-06-30 17:18 UTC
## General summary of the issue
I'm working on a script that I have a bunch of Pester tests for (all complete successfully) and I noticed that the Code Coverage report shows some lines that are definitely covered through some of my tests (i.e. I hit them when running individual tests in debug mode). Unfortunately, I cannot share the code, hence I wonder if there are any steps I could follow to try and troubleshoot this code coverage issue myself. Once I understand where the problem is, I might be able to build a repro for the issue and share that with the commuinity.

## Describe your environment
Pester version     : 5.2.2 C:\Users\UserName\OneDrive - PPD\Documents\PowerShell\Modules\Pester\5.2.2\Pester.psm1
PowerShell version : 7.1.3
OS version         : Microsoft Windows NT 10.0.19042.0

## Steps to reproduce
Here's a part from the build script that I use to trigger the Pester tests:
```posh
$configuration = [PesterConfiguration]::Default

$configuration.TestResult.Enabled.Value = $true
$configuration.TestResult.OutputPath.Value = (Join-Path $Artifacts "TestResults.xml")
$configuration.TestResult.OutputFormat.Value = "NUnitXml"

$configuration.Run.PassThru.Value = $true

$configuration.Output.Verbosity.Value = 'Detailed'

$configuration.CodeCoverage.Enabled.Value = $True
$configuration.CodeCoverage.OutputFormat.Value = 'JaCoCo'
$configuration.CodeCoverage.Path.Value = Resolve-Path -Path "$ScriptPath\*.ps1"
$configuration.CodeCoverage.OutputPath.Value = (Join-Path $Artifacts "CodeCoverageResults.xml")

$testResults = Invoke-Pester -Configuration $configuration
```

## Expected Behavior
Lines of code that are actually executed, should not be listed in the Code Coverage report

## Current Behavior
Some lines are present in the code coverage report

**Comment by nohwnd** [comment] 2021-06-30 21:22
Do the lines have something in common? Can you anonymize them? Are those stuff like `return` etc?

**Comment by Glober777** [comment] 2021-07-02 18:47
No, I don't have any `return` statements in there. It misses a little less than a half of the script.

I'll see if I can anonymize it, but it's going to take me a while.

**Comment by Glober777** [comment] 2021-07-02 19:25
I wonder if it either removes corresponding breakpoints sooner than the're actually hit, or those are not even get set. Is it possible?

**Comment by Glober777** [comment] 2021-07-05 11:00
@nohwnd, I've tried to make an oversimplified version of the project, to repro the issue, but I cannot repro the issue there.

I did perform some more research on this issue myself, and hopefully, this might give you some clue. I set a breakpoint on the first statement in my test script, and confirmed, that all the executable lines of the tested script are indeed configured with breakpoints. I was also able to confirm that the lines of the tested script that do get listed in the code-coverage report are indeed executed, however their code-coverage specific breakpoints didn't get removed for some reason and I suspect that it could be because either `$SafeCommands` become corrupt (cleared) or just the value of `$SafeCommands['Remove-PSBreakpoint']` but can't figure of a way to confirm it, because every time when I try to evaluate `$SaveCommands` through the debugger the variable is not available (even during tests that succeed with code coverage). 

Another interesting observation (that I can't explain yet) is that the code coverage result does get better (coverage rate jumps from 65% to 85%) if I disable one of the preceding tests (by putting `-Skip` switch for its `It` block). What's odd is that the test that I'm disabling is almost identical to the others, and doesn't define any mocks.

Is there a way to provide you the project privately? If so, I'll see if I can convince the management to approve this.

Thanks!

**Comment by nohwnd** [comment] 2021-07-07 08:09
> because every time when I try to evaluate $SaveCommands through the debugger the variable is not available (even during tests that succeed with code coverage).

You are probably trying to resolve it from script session state, but it is defined in Pester module. So you'd need to do `&  (Get-Module Pester) { $script:SafeCommands }`.

> Is there a way to provide you the project privately? 

Sure, my twitter account @nohwnd has open DMs, you can send me a link to a private share there. I won't disclose any of your code and will delete it when I know the gist of the issue.

**Comment by Glober777** [comment] 2021-07-07 09:47
Hi @nohwnd, I was able to convince the management to allow sharing a slightly trimmed version of our VSCode project here, just in case if someone else would also try to tackle this issue. 

And here's the gif demonstrating the repro:
![IssueRepro_stg](https://user-images.githubusercontent.com/18121861/124737820-007c6800-df21-11eb-9d73-6255634a0cd1.gif)

**Comment by Glober777** [comment] 2021-07-07 09:48
Here's the archived VSCode project:
[IssueRepro.zip](https://github.com/pester/Pester/files/6776142/IssueRepro.zip)

**Comment by Glober777** [comment] 2021-07-23 08:36
Hey @nohwnd, did you by chance had time to took a look at this?

**Comment by nohwnd** [comment] 2021-07-23 13:23
I did have a look and could repro, but did not come up with the actual issue yet, unfortunately.

**Comment by Glober777** [comment] 2021-07-24 10:01
Hey @nohwnd, I've been wondering how does debugger understands that the `$SafeCommands` should be looked for in the Pester module scope when it executes the action block? Would adding the following to the action block of breakpoints make things run more consistently?:
```
& (Get-Module Pester) { $script:SafeCommands['Remove-PSBreakpoint'] }
```

Or maybe, add a public cmdlet, like `Invoke-PesterSafeCommand -name 'Remove-PSBreakpoint'` to call the proper Remove-PSBreakpoint?

**Comment by fflaten** [comment] 2021-07-24 12:18
> I've been wondering how does debugger understands that the `$SafeCommands` should be looked for in the Pester module scope when it executes the action block? 

The action-scriptblock is created/defined inside a Pester-module function which binds the action-scriptblock to the Pester-state. This means it will always run inside the Pester-state and be able to see the module-internal `$script:SafeCommands` variable no matter where it's executed (unless someone modifies the scriptblock ofc).

Interactively, if you step into one of Pester's own functions in the debugger, you'd be able to check the variable directly, but when you're at a line in another module or script, you'd have to use `& (Get-Pester) { $Safe... }` as mentioned above to look in the right state.

Btw. if you move the weird test so it's not the first test in the script, you'd get the 85% coverage again.
![image](https://user-images.githubusercontent.com/3436158/126867961-0984e6db-9583-4f22-b33c-fad0285d5c6b.png)
Left side has "weirdtest" as the first test, while the right has it as the second test. Notice how the yellow lines aren't covered anymore. I can see them (ex. 164 + 165) being invoked in the "with members" test when i step through the code. As far as I can see, all the breakpoints looks correct at that point but for some reason the action is just not triggered.

**Comment by nohwnd** [comment] 2021-07-28 10:27
This seems like a bug in the powershell debugger. The issue is actually the way you call the New-SharedMailbox.ps1 script. The invocations differ in case, and the first one that is encountered is the use that is used. When you run your "weird test", the debugger somewhere saves that the script is spelled with capital M in Message. And we end up hitting breakpoints only for the first invocation.

When you skip the test, the first encounter will me with lowercase m which is used in all the other tests, apart from the weird one.

Here is a repro for powershell 5.1 and 7.1: 

```powershell
# file script.ps1
$null = "hello"
```
```powershell
# file justRun.ps1
Get-PSBreakpoint | Remove-PSBreakpoint
# casing here does not matter (on Windows)
$null = Set-PSBreakpoint $PSScriptRoot\script.ps1 -Line 1 -Action { Write-Host "BP on Line $($_.Line) in $($_.Script) was hit" }

# the first casing is probably saved in the debugger into some non-case insensitive cache
# probably into compiled scripts, or somewhere else, the first time we encounter the script
# determines the casing that will work
& $PSScriptRoot\script.ps1
& $PSScriptRoot\script.ps1
# this call differs in casing and the BP won't be hit
& $PSScriptRoot\Script.ps1

# if both invocations use the same casing, both BPs are hit
# it does not matter if you use & or . to invoke the script
# content of the script does not matter

```

I did not check in powershell repo if the issue is known. 

In VSCode it also works form time to time. If you step close enough to the breakpoint using the Step Into, somehow the breakpoints will start to get hit.

This also uncovered a bug in the new coverage, I am not checking the path case insensitively, I am not sure if this is a bug, or powershell simply passes the file as is. I need to decide if we should check the path case insensitively always (more convenient), or check case sensitively (will lead to weird issues like this on Windows / other non-case insensitive file systems). Imho having script files that only differ in case is edge case, that should be avoided, and checking the path case insensitively is the better way to go. On Linux user will fail to run the file (unless they actually have multiple that differ in case, and then they would get broken "merged" CC results).

**Comment by fflaten** [comment] 2021-07-28 12:37
Awesome catch 🎉 Did you just notice the case difference and try it or are there any tricks to output breakpoint condition evaluation?

**Comment by Glober777** [comment] 2021-07-28 13:20
@nohwnd, this is an awesome find! How did you figure it out? 

Once I updated all the script name references in the test script it worked out.

**Closed** 2022-07-28 13:33 UTC
Labels: Code coverage

**Comment by nohwnd** [comment] 2022-08-03 05:36
I don't remember how I figured it out, but I think it is more than likely that I just noticed the naming difference, and went from there without any special tricks.
