### ISSUE TITLE
Verbose output is printed from Describe despite specifying -Verbose:$False when $VerbosePreference is Continue

### ISSUE THREAD

**Issue by EliteLoser** [pester/Pester#921] opened 2017-10-22 04:16 UTC
Code to reproduce:

```
$VerbosePreference = "Continue"
Import-Module -Name Pester -Verbose:$False # works here
Describe -Verbose:$False foo { # stuff gets printed when you call Describe
}
"Pester version: $((Get-Module -Name Pester).Version)"
"Windows version: $((Get-WmiObject -Class Win32_OperatingSystem).Caption)"
"PowerShell version: $($PSVersionTable.PSVersion.ToString())"
```

I would like for Describe's verbose output to not be printed if you specify -Verbose:$False explicitly, despite $VerbosePreference being "Continue", as is expected behavior.

Output for me is:

```
VERBOSE: Exporting function 'EnterTestGroup'.
VERBOSE: Exporting function 'LeaveTestGroup'.
VERBOSE: Exporting function 'AddTestResult'.
VERBOSE: Exporting function 'AddSetupOrTeardownBlock'.
VERBOSE: Exporting function 'GetTestCaseSetupBlocks'.
VERBOSE: Exporting function 'GetTestCaseTeardownBlocks'.
VERBOSE: Exporting function 'GetCurrentTestGroupSetupBlocks'.
VERBOSE: Exporting function 'GetCurrentTestGroupTeardownBlocks'.
VERBOSE: Exporting function 'EnterTest'.
VERBOSE: Exporting function 'LeaveTest'.
VERBOSE: Exporting variable 'Strict'.
VERBOSE: Exporting variable 'Show'.
VERBOSE: Exporting variable 'TagFilter'.
VERBOSE: Exporting variable 'ExcludeTagFilter'.
VERBOSE: Exporting variable 'TestNameFilter'.
VERBOSE: Exporting variable 'SessionState'.
VERBOSE: Exporting variable 'CommandCoverage'.
VERBOSE: Exporting variable 'InTest'.
VERBOSE: Exporting variable 'TestResult'.
VERBOSE: Exporting variable 'TotalCount'.
VERBOSE: Exporting variable 'Time'.
VERBOSE: Exporting variable 'PassedCount'.
VERBOSE: Exporting variable 'FailedCount'.
VERBOSE: Exporting variable 'SkippedCount'.
VERBOSE: Exporting variable 'PendingCount'.
VERBOSE: Exporting variable 'InconclusiveCount'.
VERBOSE: Exporting variable 'IncludeVSCodeMarker'.
VERBOSE: Exporting variable 'TestSuiteName'.
VERBOSE: Exporting variable 'TestActions'.
VERBOSE: Exporting variable 'TestGroupStack'.

Describing foo
Pester version: 4.0.8
Windows version: Microsoft Windows 10 Enterprise
PowerShell version: 5.1.15063.674
```

**Comment by dlwyatt** [comment] 2017-10-23 00:39
That output is coming from Import-Module, not from Describe.

**Comment by dlwyatt** [comment] 2017-10-23 00:47
That output is coming from New-Module, which Pester calls internally to set up an object tracking its state.  I have no idea why it's outputting Verbose stuff when the calling code has `$VerbosePreference` set to SilentlyContinue.  Seems like a possible PowerShell bug to me.

**Comment by it-praktyk** [comment] 2017-11-01 19:10
@EliteLoser, can you consider open a bug for [PowerShell](https://github.com/powershell/powershell)?

**Comment by EliteLoser** [comment] 2017-11-03 07:59
I made an attempt with this: https://github.com/PowerShell/PowerShell/issues/5325 -- wish us luck.

**Comment by EliteLoser** [comment] 2017-11-03 08:35
Is closing this the correct thing to do now...?

**Comment by it-praktyk** [comment] 2017-11-03 09:46
The issue has minimal impact on Pester so closing it is OK. Thank you.

**Comment by mklement0** [comment] 2017-11-05 02:54
The issue only surfaces if you set `$VerbosePreference = "Continue"` _globally_.

From a _script_ - unless you use `$global:VerbosePreference = "Continue"` explicitly - you wouldn't see that behavior, because the Pester-internal `New-Module` call wouldn't see the script's variable.

I suppose that Pester functions could perform its internal `New-Module` invocation in a manner that passes their own effective verbosity setting through.

**Comment by mklement0** [comment] 2017-11-06 12:26
PS.: If  you were looking to turn off verbose output _in the script block_ passed to `Describe`, 
passing `-Verbose` to `Describe` itself is not the right approach anyway.
Instead, place `$VerbosePreference = 'silentlycontinue'` inside the script block:

```powershell
Describe foo   { 
  $VerbosePreference = 'silentlycontinue'
  write-verbose 'no' 
}
```

**Comment by EliteLoser** [comment] 2017-11-07 03:39
I notice it happens when you press F5 to run the script in ISE, but not if you call it from the command line.

This example below, showing it called from the command line, does not print verbose output from New-Module - code as in the first example I provided to reproduce - try that in PowerShell ISE and press F5, and you should the behavior I saw, with the verbose output.

I often run scripts with F5 since it's less typing, especially if you're in another directory. Guess I should move to VSCode (where I would have to type more?), but I'm sometimes a bit slow to adopt new technology.

```
> ..\PesterVerboseBug.ps1

Describing foo
Pester version: 4.0.8
Windows version: Microsoft Windows 10 Enterprise
PowerShell version: 5.1.15063.674
```

**Comment by mklement0** [comment] 2017-11-07 04:11
I see: from the _ISE_, your code indeed gets run in the _global_ scope, explaining your symptom.
As you imply, this wouldn't happen in VS Code (where <kbd>F5</kbd> would do just fine).

I agree that it makes for sense for the internal `New-Module` call to explicitly use the enclosing function's (`Describe`, in this case) effective `-Verbose` setting for consistency, but, again, what is the purpose of passing `-Verbose` to `Describe`, given that it only applies to `Describe` _itself_, not to the script block passed to it?

**Comment by mklement0** [comment] 2017-11-07 04:17
@EliteLoser:

I see: from the _ISE_, your code indeed gets run in the _global_ scope, explaining your symptom.
Note that this would happen in VS Code as well (where you can also just press <kbd>F5</kbd>).

I agree that it makes for sense for the internal `New-Module` call to explicitly use the enclosing function's (`Describe`, in this case) effective `-Verbose` setting for consistency, but, again, what is the purpose of passing `-Verbose` to `Describe`, given that it only applies to `Describe` _itself_, not to the script block passed to it?

**Comment by EliteLoser** [comment] 2017-11-07 04:37
My expectation from the code example below was/is that nothing would get printed from whatever `Describe` does behind the scenes (and anything it subsequently calls) - and that my "Hi" still gets printed, without passing -Verbose explicitly to Write-Verbose there. Probably a corner case only I care about? It's about the inverting the behavior thing, I guess.

Actually, it boils down to "Write-Host considered harmful", sort of (Snover blog post), and that the alternative, for something you always wanted printed (especially pre-v5 where passing a .ps1 to `$CaptureWriteHost = cmd /c powershell -File whatever.ps1` - was the only workaround I found for capturing Write-Host output), could be Write-Warning, and indeed Write-Verbose "message" -Verbose, but is that considered good practice? This is going off on a tangent...

Inverting Write-Verbose is related to this, but not completely overlapping.. It's something I've found myself wondering about a few times.

```powershell
$VerbosePreference = "Continue"
Describe -Verbose:$False foo {
    Write-Verbose -Message "Hi" # should get printed, nothing else
}
```

**Comment by mklement0** [comment] 2017-11-07 12:19
I realize I had a misconception about whether `-Verbose` passed to an advanced function _normally_, _by default_ propagates that setting to script blocks it invokes directly. Indeed it does, as the following snippet demonstrates.

```powershell
# Define a script block with verbose output.
$sb = { Write-Verbose 'hi' }

# An advanced function that invokes a  script block passed to it.
function foo ([Parameter()] [scriptblock] $sb) { & $sb }

# Prints 'hi' - the function's -Verbose switch is effectively propagated
# to the script block.
foo -Verbose $sb

# Does NOT print 'hi' - -Verbose is not propagated.
Describe -Verbose foo $sb
```

So, because of how `Describe` is implemented (which I know nothing about), it does _not_ propagate, though I _suspect_ that the internal use of `New-Module` is responsible for both potentially problematic behaviors discussed here:

* `Describe` unexpectedly producing verbose output from what it does behind the scenes despite being told not to (because it respects the _global_ `$VerbosePreference` value, not the enclosing advanced function's) - note that this may be related to a larger problem: https://github.com/PowerShell/PowerShell/issues/4568
   * You could also make the case that Pester should simply _categorically_ suppress verbose output from its internal `New-Module` call.

* `Describe` not propagating its effective `-Verbose` setting to the script block invoked.

To me it would make sense to indeed make `Describe` propagate the `-Verbose` setting, as would happen if `New-Module` weren't in the picture, which is arguably an implementation detail.

Note that that contravenes your expectation, however, and you'd then have to modify your code as follows:

```powershell
$VerbosePreference = "Continue"
Describe -Verbose:$False foo {
    $VerbosePreference = "Continue"  # turn verbose output on on for this script block
    Write-Verbose -Message "Hi"
}
Write-Verbose -Message "Hello!"
```

**Comment by fflaten** [comment] 2021-06-02 17:04
v4 is not actively maintained anymore so this won't be fixed there. The issue is relevant, but different in Pester v5 so not sure how we'd like to proceed with this.

**The good in Pester v5:** The noisy `New-Module`-related messages are gone due to design changes 🎉
**The still not perfect**:
- `$VerbosePreference` isn't passed from Discovery to the Run-phase, so you'd have to set it in both `BeforeDiscovery` and `BeforeAll/-Each/It` (run/execution phase) depending on where you need to control it.
- Common parameter `-Verbose` are still not respected in ex. `Describe` in any of the phases. It's ignored by `Invoke-Pester` in general to avoid messing up tests etc.

Not sure what the expected behavior is. 
- The idea is that Run-phase should be clean, so I personally wouldn't expect a script-level variable to be passed automatically from Discovery to Run. I'd recommend setting it using `BeforeAll/-Each/It` like mentioned above to be explicit when you need to control it. Worst case set it globally like `$global:VerbosePreference = 'Continue'` which will affect both Discovery and Run
- Do we expect the common parameters to work at all? We jump a lot between states and scopes, so it gets both complicated and might "corrupt" the clean test blocks. I'm wondering if it's better to document the limitation in this issue and explicitly set the `$VerbosePreference` in the blocks you need it.

The original noise OP tried to hide is gone in Pester v5 either way, so... case closed?

**Closed** 2021-06-03 08:20 UTC
Labels: Bug - external to Pester, Waiting for closure
