### ISSUE TITLE
Please consider obtaining a code signing certificate

### ISSUE THREAD

**Issue by potatoqualitee** [pester/Pester#999] opened 2018-02-24 20:57 UTC
## 1. Provide a general summary of the issue in the Title above

First, Pester is *awesome* and people are *loving* it. We created a framework around Pester with dbchecks and the reception has been very positive.

I saw #900 and know it's a known limitation but have a proposed solution below.

## 3. Expected Behavior

Pester is catalog signed

## 4.Current Behavior

Pester is not catalog signed

## 5. Possible Solution

1. DigiCert offers free Code Signing Certs for MVPs.

 2. An alternative is to setup a Trade Name and sign it but if it's not under a personal name, DigiCert does charge. In order to ensure dbatools is signed under a trade name, I reached out and asked the community to help us purchase a code signing certificate. Two community members purchased a 3 year certificate for us.

## 6. Context

We include Pester as a required module in dbachecks and have to explicitly say everywhere how to first update Pester the manual way. 

`Install-Module Pester -SkipCatalogCheck -Force`

Even though we state this everywhere, we still get questions.

Also, we signed our module but realized it's not as useful if all required modules are not signed. I can get our other module, PSFramework, signed but won't pursue that avenue without Pester being signed.

**Comment by dlwyatt** [comment] 2018-02-24 21:06
If I remember correctly, it won’t help.  The version of Pester shipped with windows is catalog signed by Microsoft. PowerShellGet would still complain if we sign new versions with a non-MS cert.

**Comment by potatoqualitee** [comment] 2018-02-24 21:09
Seems unlikely but I'm always hopeful - perhaps Microsoft would consider using your cert in future Windows releases.

**Comment by bergmeister** [comment] 2018-02-25 21:40
Pester has already been removed from PowerShell Core and @steveLMsft has also thought of removing it from Windows PowerShell in 5.2 (although not sure what the final decision is)

**Comment by SteveL-MSFT** [comment] 2018-02-26 06:39
@bergmeister Current decision by PS-Committee is to not make any change in Windows PowerShell so to not introduce a regression.  The issue with PowerShellGet can be solved by PowerShellGet team.

**Comment by potatoqualitee** [comment] 2018-02-26 07:07
Thanks @bergmeister and @SteveL-MSFT. I'd be happy with any solution that isn't repeatedly having to educate users about `-SkipPublisherCheck -Force`. Who is best to approach about making an exception within PowerShellGet for Pester?

Thanks again,
Chrissy

**Comment by SteveL-MSFT** [comment] 2018-02-26 16:25
@potatoqualitee please open an issue here: https://github.com/powershell/powershellget, I think if the publisher is trusted even if the publishing cert changed, PowerShellGet shouldn't stop the install (perhaps a Warning is ok).

**Comment by nohwnd** [comment] 2018-02-27 08:47
Can we do anything about this, or should I close this issue?

**Comment by potatoqualitee** [comment] 2018-02-27 09:54
Thanks for the quick response and feedback, everyone!

**Comment by kilasuit** [comment] 2018-07-24 11:00
this can be reopened considering the update at  https://github.com/PowerShell/PowerShellGet/issues/233

@nohwnd  if you can code sign pester that will fix the issue here and in PowerShellGet

**Comment by nohwnd** [comment] 2018-12-13 07:19
Version 4.4.3 is the first signed version, now I just need to keep them signed in the future as well.

**Closed by nohwnd** 2018-12-13 07:19 UTC

**Comment by webguynj** [comment] 2019-01-03 17:44
Seems that even with this release that Pester is complaining about the signed certificate this way:
`S C:\Windows\system32> Install-Module -Name Pester -Force -RequiredVersion 4.4.3
PackageManagement\Install-Package : A Microsoft-signed module named 'Pester' with version '3.4.0' that was previously
installed conflicts with the new module 'Pester' from publisher 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com,
O=DigiCert Inc, C=US' with version '4.4.3'. Installing the new module may result in system instability. If you still
want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21`

**Comment by bergmeister** [comment] 2019-01-03 18:01
Hmm, yes, but this is just PowerShellGet being a jerk as usual  if you run `Install-Module PowerShellGet -Force` to update to a newer version of it, then it should be better

**Comment by kilasuit** [comment] 2019-01-04 03:21
you might actually need both `-SkipPublisherCheck` and `-Force` due to the way that the Publisher Check works 

Or if you have Admin on your machine (or can get an admin to do this) then deleting the Pester 3.4.0 version completely from your system will get rid of that error completely ( though might need to take control from Trusted Installer account to do so IIRC)

**Comment by nohwnd** [comment] 2019-01-04 14:14
Since `1.6.3` version of PowerShellGet There is exclusion for Pester and PSReadline (described in the referenced issue), so the `-SkipPublisherCheck` should not be needed. Unless you install Pester is not signed (before `4.4.3`) or you are using PowerShellGet that is older than `1.6.3`. In both cases I can only recommed updating.

To remove the previous built-in version of Pester from your system you do have take ownership and reset permissions, [here is a script](https://gist.github.com/nohwnd/5c07fe62c861ee563f69c9ee1f7c9688) that automates the whole process. Then you will have no warnings as @kilasuit said.
