### ISSUE TITLE
Is there a BeforeEachContext?

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#335] opened 2015-04-28 19:06 UTC
Issue #325 demonstrates that sometimes an explicit mock call history must be maintained.  That naturally [looks something like this](https://github.com/pester/Pester/issues/325#issuecomment-97150581).  I've started using that approach this and have discovered the following:
- it is common to have a single `Describe` block with multiple `Context` blocks each of which you would naturally want to have a fresh call history
- accordingly, you naturally call `$callHistory.Clear()` at the beginning of the first `It` block in each `Context` block
- it is easy to miss one of the `$callHistory.Clear()` if you have a multitude of `Context` blocks, with rather confusing results.

A scriptblock that is executed before each context block would pretty much solve this problem.  Is there a `BeforeEachContext` cmdlet or some other way to have a single scriptblock execute before each context?

**Comment by dlwyatt** [comment] 2015-04-28 19:59
There's nothing like that at the moment.  I'd like to avoid hard-coding more references to the Describe/Context structure, though.  At some point we want to be able to arbitrarily nest test groups.

Maybe something like BeforeEachSuite, or BeforeEachGroup?  These would probably define blocks that behave the same way as if you'd used BeforeAll / AfterAll in every child block of the scope where you used the command (including nested Describes / Contexts, once those are supported.)

**Comment by alx9r** [comment] 2015-04-29 00:03
I think I see what you mean.  So we'd end up with a command that says "run this scriptblock before each `Describe`/`Context`/`It` that is a *direct* child of this scope."  That would solve this problem.

I'm not sure what it should be called, but `BeforeEachGroup` sounds intuitive to me.

**Comment by dlwyatt** [comment] 2015-04-29 01:16
> that is a _direct_ child of this scope

What about nested child groups?

**Comment by alx9r** [comment] 2015-04-29 03:05
@dlwyatt I'm not quite sure what you mean by "nested child groups" here.

The important thing for clearing the call history is that it is called before each scope that groups some `It` blocks but not before each individual `It` block.  I can imagine a number of ways to describe that, but I'm not sure what makes most sense for the future of Pester.

**Comment by dlwyatt** [comment] 2015-04-29 03:11
Well, let's assume for the moment that this is legal (because something like it will be, eventually):

```posh
Describe 'L1' {
    BeforeEachGroup { $hash = @{ someKey = 'Whatever' } }

    Describe 'L2' {
        $hash.someKey = 'Set in L2'

        Describe 'L3' {
            # Should $hash.someKey be 'Whatever' here, or 'Set in L2'?
            # Depends on whether the BeforeEachGroup block applies recursively to all child test groups,
            # or only to the immediate children of the group that contains the call to BeforeEachGroup.
        }
    }
}
```

**Comment by nohwnd** [comment] 2015-04-29 08:10
@alx9r Thanks for filling out so many issues, having these conversations is great :+1:. 
I can't agree that explicit mock called history must be maintained, and so you can use mock call history Pester offers internally. You can then use the `-Scope` parameter of `Assert-MockCalled` to limit the scope of calls you want to assert on. 

Setting up mocks should be, in my point of view, done locally. That is as close to the test case as possible. That way you can easily see what you have mocked for a given test and your Mock definitions won't bleed from one test case to another.

Even if BeforeEachContext/AfterEachContext (or BeforeEachGroup as @dlwyatt calls it) was implemented I would use it cautiously. 

The BeforeEach and AfterEach should be mainly used to setup the resources for the tests (`It`s). Like setting up and tearing down files, database and whatnot. But the data saved in those resources should be set in the test case, not in the Before/After block (unless you are testing tons of read-only scenarios against the same data).

The purpose of the test is then to check if the data flow through the tested function correctly. 

The BeforeAll might setup environment too, but then you will reuse the same environment for all of the tests. If any of those tests changes the state of the environment all your tests will become dependent on the order they are called. That is something I would try to avoid. 

On the other hand, using AfterAll to make sure your environment was properly teardown and cleaned up is great feature to have.

**Comment by alx9r** [comment] 2015-04-29 14:45
@dlwyatt I suppose either might be needed at some point.  `Get-ChildItem` uses `-Recurse`.  Is there a reason `BeforeEachGroup -Recurse { ... }` wouldn't work?  That would be idiomatic and follows a pattern most Powershell users are already familiar with.

**Comment by dlwyatt** [comment] 2015-04-29 14:59
Makes my job harder.  :)  BeforeEach / etc look like normal commands, but they don't actually do anything when "called" by PowerShell:

```posh
function BeforeEach
{
<#
.SYNOPSIS
    Defines a series of steps to perform at the beginning of every It block within
    the current Context or Describe block.

.DESCRIPTION
    BeforeEach, AfterEach, BeforeAll, and AfterAll are unique in that they apply
    to the entire Context or Describe block, regardless of the order of the
    statements in the Context or Describe.  For a full description of this
    behavior, as well as how multiple BeforeEach or AfterEach blocks interact
    with each other, please refer to the about_BeforeEach_AfterEach help file.

.LINK
    about_BeforeEach_AfterEach
#>
    Assert-DescribeInProgress -CommandName BeforeEach
}
```

Instead, when you enter a Context or Describe, Pester parses the contents of that command's script block, looking for calls to BeforeEach / etc, and sets them up for execution.  This allows you to define your BeforeEach / etc blocks in any order, and they'll still work.

In PowerShell 3.0 and later, this code now uses the AST to do the parsing, and adding parameters to the commands would be pretty straightforward.  For PowerShell 2.0, however, the parsing is something I wrote (since the AST didn't exist in a public form), and it would be a headache to start adding switches and such.

**Comment by ashleybartlett** [comment] 2015-11-13 03:14
Something like a BeforeEachContext could be very useful. 

I have written some tests, where withing each context I call the function I am testing, stores the output, and I run multiple tests against that output. 

But I like to setup some in the Describe level that can get modified in tests, and so I have a BeforeEach setup under Describe, but that isn't run at the Context level (or at least, it was at some point, and wasn't in my most recent test). So in the example below, I get an error, as $var1 does not exist at the root of the Context.  Would be nice to use a BeforeEachContext type function. Or a BeforeEach -scope Context

```powershell
Descibe 'Root Test' {
    BeforeEach {
        $var1 = @{ a='1'; b='1'};
    }

    Context 'Sub 1' {
        $out = fun-function -input $var1

        it 'Outputs expected' {
            [...]
        }
    }

}
```

**Comment by nohwnd** [comment] 2019-03-24 12:55
This is partially duplicate of #1219 where I will be implementing the BeforeEach BeforeAll. Recursive block setups are either already working or easy to add. 

Clearing mock history is imho not needed if you place the mock in the correct place, if it turns out to be needed, we can open another issue or re-open thins one.

**Closed by nohwnd** 2019-03-24 12:55 UTC
Labels: Feature, Question
