### ISSUE TITLE
Dashes in wiki page titles are silently replaced with spaces

### ISSUE THREAD

**Issue by it-praktyk** [pester/Pester#688] opened 2017-01-20 00:32 UTC
Dashes in wiki page titles are silently replaced with spaces - the effect is like on the screenshot below.

![selection_010](https://cloud.githubusercontent.com/assets/4910261/22130730/7199cbd6-deae-11e6-9dee-970f0f6ef970.png)

Known workaround - I used it for the subpage [Set-TestInconclusive](https://github.com/pester/Pester/wiki/Set%E2%80%90TestInconclusive) - is use the Unicode char [Hyphen](https://unicode-table.com/en/2010/) like described [here](https://github.com/gollum/gollum/issues/764#issuecomment-273856568).

Only dashes in articles titles need to be changed/corrected.

Possible impact:
- all refferences to Wiki - e.g. like that included in [The Pester Book](https://leanpub.com/the-pester-book) will be broken.
- links in code (if they are) to wiki need to be corrected too

What do you think?

CC: @adbertram , @concentrateddon

**Comment by nohwnd** [comment] 2017-01-20 07:22
There probably is a lot of a links between the wiki pages, I need to find a way to find them all to see what we are dealing with.

**Comment by it-praktyk** [comment] 2017-08-18 06:43
The related issue: https://github.com/gollum/gollum/issues/764.

**Comment by adbertram** [comment] 2017-08-18 12:09
There are a lot of links in the Pester Book. I can fix them if you need to change the scheme. I should probably just pass those through a URL shortener anyway.

**Comment by johnmbaughman** [comment] 2019-05-22 19:59
It appears that the problem is caused by the fact that the file names use dashes as a delimiter/replacement for spaces. These file names are also used as the larger title. To resolve this, clone the repository, rename the specific files using `%2D` for the dash you want. Of course, renaming the link in the appropriate wiki doc will also require this. 

Original: 

`New-MockObject.md`

New: 

`New%2DMockObject.md`

**Comment by nohwnd** [comment] 2019-05-23 06:59
@johnmbaughman thx

**Comment by binaryjeff** [comment] 2019-06-29 12:47
I've never contributed to an open source project before, but I saw this "help wanted" issue.  The `%2D` didn't work for me.  Github does not convert them to hyphens.

I ended up following the advice of [gollum/gollum#764](https://github.com/gollum/gollum/issues/764) and using a unicode character.  I took the opportunity to make the headings & formatting more consistent through all the pages.  It doesn't look like you can do pull requests for wikis?  Perhaps you can review my changes here and let me know what you think:

Live wiki: [binaryjeff/Pester-wiki/wiki](https://github.com/binaryjeff/Pester-wiki/wiki)

Code: [binaryjeff/Pester-wiki](https://github.com/binaryjeff/Pester-wiki)

There wasn't as many cross-page links in the code as I was anticipating.

**Comment by nohwnd** [comment] 2019-06-30 11:14
@binaryjeff thanks for the contribution. Sadly you can't do PRs for wiki. The only way for you to merge and push your wiki would be to be added to the project, but that would give you way more permissions than I am comfortable granting. Github is stupid in this. I will try to pull the repo and merge the branch from your remote. That way you it hopefully keeps you as the author of those changes.

**Comment by nohwnd** [comment] 2019-06-30 11:15
@binaryjeff Other than that the wiki is open for contributions, and you (or anyone) can make them online because it is open for modification.

**Comment by nohwnd** [comment] 2019-06-30 11:22
Merged. 

@adbertram you might want to review your links to the wiki.

**Closed by nohwnd** 2019-06-30 11:22 UTC
Labels: Documentation, Help Wanted
