### ISSUE TITLE
Missing Parameter Docs in V5

### ISSUE THREAD

**Issue by LethiferousMoose** [pester/Pester#2128] opened 2022-01-31 04:21 UTC
## Location

- Pester version: v5
- Functions: `Should`, `Get-ShouldOperator`

## General summary of the issue
Placeholder text is still being used for parameter documentation.

**Comment by fflaten** [comment] 2022-01-31 18:55
Thanks for the report. This is a known limitation due to use of dynamic parameters in both functions.

We should be able to fix `-Name` in `Get-ShouldOperator`, so I'm keeping this open for that as a minimum.

`Should` is a bit more difficult. It has two types of parameters:
- Operators name/alias: The name of the operator to use. Can only chose one at a time (as it defines the parameter set)
  - We could possibly include the synopsis for the operator-name, example:

> ### -Exist
> 
> Does not perform any comparison, but checks if the object calling Exist is present in a PS Provider.
> The object must have valid path syntax. It essentially must pass a Test-Path call.
> 
> ```yaml
> Type: SwitchParameter
> Parameter Sets: Exist
> Aliases: 
> Accepted values: 
> 
> Required: True (None) False (Exist)
> Position: Named
> Default value: 
> Accept pipeline input: False
> Accept wildcard characters: False
> DontShow: False
> ```

- Operator input: Parameters like `-ExpectedValue`, `-Times`, `-Exactly`, `-ErrorId` etc. which could have different meanings for each operator.
  - It looks like PowerShell will select the last helpmessage for a parameter used in multiple parameter sets (operators in our case), so we might pick a random text that only fits one operator.
  - Might be better to just leave it blank, or hardcode a message like:

> ### -ExpectedValue
> 
> Depends on operator being used. See `Get-ShouldOperator -Name <Operator>` for help.
> 
> ```yaml
> Type: Object
> Parameter Sets: Be, BeExactly, BeGreaterThan, BeLessOrEqual, BeIn, BeLessThan, BeGreaterOrEqual, BeLike, BeLikeExactly, Contain, HaveCount
> Aliases: 
> Accepted values: 
> 
> Required: True (None) False (Be, BeExactly, BeGreaterThan, BeLessOrEqual, BeIn, BeLessThan, BeGreaterOrEqual, BeLike, BeLikeExactly, Contain, HaveCount)
> Position: 1
> Default value: 
> Accept pipeline input: False
> Accept wildcard characters: False
> DontShow: False
> ```

Would that help? Not sure if the theory works all the way back to PSv3 though.

**Comment by LethiferousMoose** [comment] 2022-02-02 03:06
How do you create your docs? Do you use platyPS? Does it pull straight from the PowerShell code or is the markdown the source of truth? If the markdown was the source of truth you could just update that file could you not? It clearly generated placeholder text. I was less concerned about the `Get-Help` in actual PowerShell and more concerned the actual docs website is missing information.

**Comment by fflaten** [comment] 2022-02-02 05:27
We use platyPS with code as truth. It's done through a Docusaurus helper-module which always use `new-markdownhelp`, so we'd want to always get the parameter help from code.

I was mostly thinking about description examples. Synopsis for operators can be rephrased. However I wouldn't personally like 10 lines for description of `-ExpectedValue`, `-Because` etc. because we had to include it's help per operator (since they could vary worst-case). So some type of static text is probably best for the non-operator/input parameters.

AFAIK get-help doesn't work with dynamic parameters, so web only for parameters.

**Comment by LethiferousMoose** [comment] 2022-02-02 05:53
Okay, well if you're always using `New-MarkdownHelp` it looks like it will pull off the `HelpMessage` from a runtime parameter. I just did a test and that will pre-populate the `{{ }}` placeholders.  I'm not sure how Pester creates it's runtime parameters, but you could just add some general descriptive text in there. Does the usage vary that much? When it comes down to do it, they are fairly general assertions.

**Comment by fflaten** [comment] 2022-02-02 06:04
> it will pull off the `HelpMessage` from a runtime parameter. 

Yeah that's the plan 👍

> Does the usage vary that much?

Don't remember all in my head, but can't ignore the possibility. The issue is still that since it uses the last attribute's helpmessage, it could also break in the future when new operators are added or code is reordered.

Maybe I'm overthinking this. Currently no parameter help in operators so it all has to be written too. Was hoping to simplify that part by referencing the official assertion help-pages. 🙂

**Comment by LethiferousMoose** [comment] 2022-02-02 06:13
Oh right, I forgot the parameter sets are all in different attributes. I see what you're getting at now. That could be a pain to maintain...

**Comment by fflaten** [comment] 2022-12-27 09:34
Should be fixed after next update if docs when 5.4 is released.

**Closed** 2023-01-11 15:12 UTC
Labels: Documentation
