### ISSUE TITLE
Testing module Pester doesn't fail if function doesn't exist if autoloading can find one

### ISSUE THREAD

**Issue by simonsabin** [pester/Pester#2027] opened 2021-07-13 08:32 UTC
I'm trying to test a module and find often that for whatever reason files are missed being included. The net result is that on a CI agent that doesn't have the module installed it fails, but locally the tests pass because powershell autoloads finds the function in a previous version of the module already installed. 

Beyond uninstalling ALL versions of a module. There doesn't appear to be a way to get these tests to fail on the local machine. 

I've tried setting psmodulepath, and PSModuleAutoloadingPreference but they seem to be being ignored. I assume due to the way that pester is now running tests. 

## Steps to reproduce
Create a test for a function installed on your machine but not on the build agent.

Run your test locally

## Expected Behavior
Test should

## Current Behavior
Test passes

## Possible Solution? (optional)
Prevent autoloading of modules, setting psmodulepath

**Comment by nohwnd** [comment] 2021-07-14 15:52
Pester does not do anything special regarding module loads. Or I am not aware of it. Do you have a repro? Is the PSModuleAutoloadingPreference ignored? Do you set it as $global?

**Comment by simonsabin** [comment] 2021-07-14 16:16
I wasn't setting it at global. Whats odd is that I can't seem to be able to override psmodulepath. Its like Pester is setting it somehow.
I'd love to know how others are testing modules and avoiding "bringing in existing functions from installed modules"

**Comment by nohwnd** [comment] 2021-07-19 17:50
You probably should set is as global.

**Comment by fflaten** [comment] 2022-07-17 09:30
Can't reproduce. `$PSModuleAutoLoadingPreference = 'None'` works and is not modified by Pester in any way AFAIK.

```powershell
$PSModuleAutoLoadingPreference = 'None'
Import-Module C:\Modules\pester\5.3.3\Pester.psd1
Invoke-Pester c:\git\pester\samples\demoModuleAutoLoad.tests.ps1 -Output Detailed

Pester v5.3.3

Starting discovery in 1 files.
Discovery found 1 tests in 8ms.
Running tests.

Running tests from 'C:\git\pester\samples\demoModuleAutoLoad.tests.ps1'
Describing d1
  [-] Finds Pester in PowerShell Gallery 5ms (3ms|2ms)
   CommandNotFoundException: The term 'Find-Package' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at <ScriptBlock>, C:\git\pester\samples\demoModuleAutoLoad.tests.ps1:5
Tests completed in 36ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0

# Now with default autoloading
$PSModuleAutoLoadingPreference = 'All'
Invoke-Pester c:\git\pester\samples\demoModuleAutoLoad.tests.ps1 -Output Detailed

Pester v5.3.3

Starting discovery in 1 files.
Discovery found 1 tests in 7ms.
Running tests.

Running tests from 'C:\git\pester\samples\demoModuleAutoLoad.tests.ps1'
Describing d1
  [+] Finds Pester in PowerShell Gallery 3.69s (3.69s|3ms)
Tests completed in 3.74s
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

Closing as this seems to be external issue.
Maybe you tried to set it in a `BeforeAll`-block while using some of the commands during Discovery in some of the testfiles?

**Closed by fflaten** 2022-07-17 09:30 UTC

**Comment by nohwnd** [comment] 2022-08-03 05:38
I confirm that I am also not aware of Pester touching `$PSModuleAutoLoadingPreference`.

**Comment by simonsabin** [comment] 2022-08-03 08:02
I’m thinking that it’s a module setting and so you can’t set it, or something about pester is resulting in modules to be loaded before the script containing the psmoduleautoloadingpreference is set to say don’t load.

I really wish that was a whitelist of modules to load rather than an on or off. But that’s for a different forum

Simon Sabin

________________________________

**Comment by fflaten** [comment] 2022-08-03 08:15
If you're using the vscode powershell integrated console locally, then intellisense often import while analyzing commands in open files IIRC.

**Comment by simonsabin** [comment] 2022-08-03 08:20
I’m sure the test I had ensured module wasn’t loaded , set loading preference, and then called function that hasn’t been loaded but exists in a  module, and the module gets loaded.

Will try and reproduce, this might have been with 4

Simon Sabin

________________________________
