### ISSUE TITLE
Mock CommandName not correct

### ISSUE THREAD

**Issue by DarkLite1** [pester/Pester#913] opened 2017-10-16 13:32 UTC
In some very rare circumstances, which I can't seem to duplicate consistently, it happens that instead of the name of the mocked function the name of the `$TestDrive` is returned. After some debugging it appears to happen on line 169 of `Mock.ps1`:

`$CommandName = $contextInfo.Command.Name`

A screenshot to explain:
![image](https://user-images.githubusercontent.com/10828570/31614538-ff625ec2-b286-11e7-9ffe-876141cf17f7.png)

I'm sorry for not being able to reproduce this consistently. 

Test code used:
```
Describe 'My test' {
    Mock Get-ADGroupMember {
        1
    } -ParameterFilter {"MYGROUP"}

    in $testdrive {
        Describe 'test' {
            it 'Test' {
                Get-ADGroupMember -Identity "MYGROUP" | Should -BeExactly 1
            }
        }
    }
}
```

**Comment by nohwnd** [comment] 2018-02-11 10:47
Tried it about 100 times, and cannot reproduce it :/ What is your Pester version, and ad modules version?

**Comment by DarkLite1** [comment] 2018-02-12 07:40
It's a very rare thing that this happens. But I still found it worth it to report it. In case someone else experienced this too. I just checked, it is Pester version `4.1.1`.

**Comment by nohwnd** [comment] 2018-02-12 09:40
Okay I will try looping it for some time to see if it ever happens to me :)

**Comment by DarkLite1** [comment] 2018-02-12 10:11
I can't duplicate it either, so it might have to do with running other Pester tests at the same time. Or mocks not being unloaded/removed. The good thing is, a screenshot doesn't lie lol. Anyhow, I hope I can pinpoint it more/better next time. If I find more I'll let you know. Thx again for the effort, much appreciated.

**Comment by DarkLite1** [comment] 2018-03-05 12:50
The error in  #1004 also refers to a Mock name that doesn't exist.

**Comment by nohwnd** [comment] 2018-04-11 19:40
@DarkLite1 @michalporeba So internally we are creating a function with guid name, and then an alias (or multiple aliases if the command is from a module) that points to it. That is how mocking works. Aliases are running out of scope automatically, but if you stop the test mid run the alias and function will remain. Then on subsequent calls the mock will pick up the alias, and resolve to the guid function. In my case the mocking still works fine, but the cause is likely the same, you are just doing something else as well. 


To replicate this, set breakpoint on `Assert-MockCalled` and stop the run. Then run it again. You should get multiple functions with guid names (do `Get-Command *-*-*-*` ).  And only one of them has the mock definition. the other simply contains the other guid (call to the other function).

```powershell
describe "a" {
    it "b" { 
        Mock Get-Content

        Assert-MockCalled Get-Content # <- breakpoint here

    }
}
```

As a remedy  the functions should probably be called Pester_<originalNames>_<guid> and we should delete all of them and the alias when starting a new Pester state.

**Comment by DarkLite1** [comment] 2018-04-12 05:52
Thank you for looking into this further. When we write production scripts here at work, we usually declare the variables empty at the top of each script. This way we prevent an incorrect or assumed state.

The workaround you suggest seems to be able to allow Pester to start clean. Which I'm turn might no longer require it to run only in a Powershell window but also in the Powershell ISE. 

Thumbs up for this idea 👍

**Comment by nohwnd** [comment] 2018-04-12 16:50
@DarkLite1 I actually stumbled upon it by accident, I was preparing a talk about Pester internals, and I got this exact issue after a while, which puzzled me for a bit. I think the clean up should be pretty simple, unless it gets complicated with cleaning up in modules. Should have a look next week or the week after that.

**Comment by it-praktyk** [comment] 2018-05-01 18:58
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.

**Comment by DarkLite1** [comment] 2018-05-02 08:30
@it-praktyk I don't think it should be closed yet, given that @nohwnd is working on a fix. Thank you for reopening in the meantime.

**Closed** 2018-05-06 09:40 UTC
Labels: Documentation, Mocking

**Comment by DarkLite1** [comment] 2018-05-07 07:04
Awesome! This will be very helpful when testing and debugging code from within the `PowerShell ISE` or `VS code`, rather than invoking `Invoke-Pester`. Thank you very much :)
