### ISSUE TITLE
Functions defined in Describe script block not visible to BeforeAll/AfterAll script block

### ISSUE THREAD

**Issue by splatteredbits** [pester/Pester#518] opened 2016-04-21 23:11 UTC
This test fixture fails with CommandNotFoundException (The term 'Test-Something' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.)

```
Describe 'BeforeAll and After' {
    function Test-Something
    {
        Write-Verbose 'In Test-Something' -Verbose
    }

    BeforeAll {
        Test-Something # fails!
    }

    AfterAll {
        Test-Something #fails !
    }

    BeforeEach {
        Test-Something # No failures
    }

    AfterEach {
        Test-Something # No failures
    }

    It 'should not do anything for purposes of this demonstration' {
        $true | Should Be $true
    }
}
```

If you remove BeforeAll/AfterAll, you'll see that Test-Something does get called from the BeforeEach/AfterEach blocks.

**Comment by dlwyatt** [comment] 2016-04-22 03:48
Hmm, tricky.  Here's essentially what Describe and Context do now:

```posh
try
{
    DotSource-BeforeAll
    Execute-DescribeBody
}
finally
{
    DotSource-AfterAll
}
```

So at runtime, both the BeforeAll and AfterAll blocks are invoked outside of the Describe body, and any functions defined inside that body don't exist.  (This also reveals a bit of a quirk with BeforeAll / AfterAll; they're actually dot-sourced into the _parent_ scope of the Describe block, not into the Describe block itself.  I hadn't really thought of that until looking at this pseudocode version.)  For example, you could work around it by putting the function definition into the BeforeAll block, but then the function would still exist even after the Describe finished:

```posh
Describe 'BeforeAll and After' {
    BeforeAll {
        function Test-Something
        {
            Write-Verbose 'In Test-Something' -Verbose
        }

        Test-Something
    }

    AfterAll {
        Test-Something
    }

    BeforeEach {
        Test-Something
    }

    AfterEach {
        Test-Something
    }

    It 'should not do anything for purposes of this demonstration' {
        $true | Should Be $true
    }
}

Get-Command Test-Something
```

BeforeAll is just never going to work that way; logically, you're trying to call a function before it's defined.  You'll have to put the function definition into a BeforeAll block, or into a parent scope of the Describe.  (And honestly, BeforeAll is a little bit pointless; why not just execute those statements first and forego the BeforeAll { } part?  I only included the command to complete the set.)

I think we can probably solve the AfterAll problem, though, and also take care of data leaking these blocks into a parent scope by modifying Describe and Context to do something along these lines:

```posh
$newScriptBlock = {
    try
    {
        DotSource-BeforeAll
        DotSource-DescribeBody
    }
    finally
    {
        DotSource-AfterAll
    }
}

& $newScriptBlock
```

The difference is that the new script block provides us with a buffer between the Describe body and the parent scope, and that the describe body is then dot-sourced into that new script block's scope (so any functions defined will be visible in AfterAll.)

**Comment by dlwyatt** [comment] 2016-04-23 20:57
Started playing around with a branch to address this today.  Other than adding another anonymous <ScriptBlock> entry to stack traces, it seems to work.  (Still need to write some tests for Pester to prevent future regression).  https://github.com/pester/Pester/compare/master...dlwyatt:AfterAllScopeFix?expand=1

When I run the test code I put in my last post, now the `Get-Command Test-Something` part will throw an error, but AfterAll will continue to work.

**Comment by felixfbecker** [comment] 2018-09-03 18:17
Shouldn't calling `.GetNewClosure()` as a user solve this?
```powershell
AfterEach {
    # ...
}.GetNewClosure()
```
should in theory enclose the scope, right?

**Comment by nohwnd** [comment] 2019-03-24 12:32
I tried to fix this in v5, and it would kinda be possible, but it would require the BeforeAll to be run inside of the current Describe right before the first It or Describe in the current Describe starts. Unfortunately that brings a lot of headaches to the scopes, and you need to think about what fails where and it's a real nightmare.

In v5 no code should be placed outside of the BeforeAll block anyway. Moving the function inside of it works, and the scoping is now corrected so the BeforeAll is scoped to the same scope as the Describe body that contains it, and not outside of it. This avoids leaking details from the block to other blocks.

Closing because there is nothing more to do here.

**Closed by nohwnd** 2019-03-24 12:32 UTC
