### ISSUE TITLE
$PSCommandPath is Null inside BeforeAll and BeforeEach but not It blocks.

### ISSUE THREAD

**Issue by alx9r** [pester/Pester#329] opened 2015-04-27 19:06 UTC
The following test demonstrates that the automatic variable `$PSCommandPath` is null inside `BeforeEach` and `BeforeAll` blocks, but not `It` blocks.

```PowerShell
Describe 'PSCommandPath is null in BeforeAll and BeforeEach.' {
    BeforeAll {
        $baCommandPath = $PSCommandPath
    }
    BeforeEach {
        $beCommandPath = $PSCommandPath
    }
    It 'PSCommandPath is null in BeforeAll.' {
        $baCommandPath | Should beNullOrEmpty
    }
    It 'PSCommandPath is null in BeforeEach.' {
        $beCommandPath | Should beNullOrEmpty
    }
    It 'PSCommandPath in It refers to fixture.' {
        $PSCommandPath.Split('.')[-2] | Should be 'Tests'
    }
}
```

## Why this Matters
In order to [test that all required modules are loaded by a module-under-test](https://stackoverflow.com/q/29021312/1404637), you need to [remove all superfluous modules in BeforeEach](http://stackoverflow.com/a/29087563/1404637).  In order to do that without unloading the module-under-test, you need to derive the name of the module-under-test inside `BeforeEach`.  If you just use a string literal inside the `BeforeEach` to determine the module-under-test, you create a maintenance problem -- particularly if you have multiple `Describe` blocks for a single module-under-test.  So, you ought to be able to get `$PSCommandPath` from `BeforeEach`.

## Workaround
There is a workaround for this problem using a global variable, but it's still not that easy to maintain.  It looks like this:

````Powershell
$Global:thisPSCommandPath = $PSCommandPath
Describe {
    BeforeEach {
        $thisPSCommandPath | Do-Something
    }
    ...
}
Remove-Variable thisPSCommandPath -Scope Global
````

**Comment by dlwyatt** [comment] 2015-04-27 19:11
The root cause of this is the same as in issue #319 .  This is easily fixed in PowerShell 3.0 and later, but not so much in PowerShell 2.0.

Not sure if I should have different versions of the BeforeEach / AfterEach parsing code within the module.  This would make it behave better for most people (who are probably using PowerShell 3.0+ anyway), but might be confusing if someone tries to test their code on PS 2.0 and their tests start to blow up due to a change in Pester's behavior.

Regardless of what happens with that decision, at some point we'll drop support for PS2.0 in new versions of Pester.  When that happens (though it may be a long way off), it will open quite a few doors for us in terms of functionality enhancements.

**Comment by alx9r** [comment] 2015-04-27 19:33
@dlwyatt Thanks very much for the clarity.

FWIW, I think powershell-version-dependent Pester behavior is far less bad than the rather large volume of hacky workarounds I have to put in test code.

**Comment by dlwyatt** [comment] 2015-04-28 06:13
I've got a PR open for this, will merge it tomorrow after the tests run.  I wasn't able to figure out how to make this work in PowerShell 2.0, but I realized that the automatic variables $PSScriptRoot and $PSCommandPath don't exist in that version anyway, which makes it kind of a moot point.

**Closed** 2015-04-28 17:01 UTC
Labels: PowerShell 2 Limitation

**Comment by alx9r** [comment] 2015-04-28 23:57
@dlwyatt Thanks! :)
