### ISSUE TITLE
Code Coverage Example Not Showing Report Output in Console

### ISSUE THREAD

**Issue by bjellesma** [pester/Pester#1864] opened 2021-03-06 22:16 UTC
Hi,

The CodeCoverage parameter for Invoke-Pester does not seem to be outputting the percentage or missed commands to my console. This is my environment

| Powershell | Version 7.1.2 Core |
| OS | Windows 10.0.19041 |
| Pester | Version 5.1.1 |

It does seem to be creating a coverage.xml file in the same directory with the following xml that makes it look like it is using code coverage. 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd"><report name="Pester (03/06/2021 16:56:59)"><sessioninfo id="this" start="1615049819721" dump="1615049819865" /><package name="pester"><class name="pester/CoverageTest" sourcefilename="CoverageTest.ps1"><method name="FunctionOne" desc="()" line="3"><counter type="INSTRUCTION" missed="1" covered="2" /><counter type="LINE" missed="1" covered="2" /><counter type="METHOD" missed="0" covered="1" /></method><method name="FunctionTwo" desc="()" line="15"><counter type="INSTRUCTION" missed="1" covered="1" /><counter type="LINE" missed="1" covered="1" /><counter type="METHOD" missed="0" covered="1" /></method><counter type="INSTRUCTION" missed="2" covered="3" /><counter type="LINE" missed="2" covered="3" /><counter type="METHOD" missed="0" covered="2" /><counter type="CLASS" missed="0" covered="1" /></class><sourcefile name="CoverageTest.ps1"><line nr="3" mi="0" ci="1" mb="0" cb="0" /><line nr="5" mi="1" ci="0" mb="0" cb="0" /><line nr="9" mi="0" ci="1" mb="0" cb="0" /><line nr="15" mi="0" ci="1" mb="0" cb="0" /><line nr="16" mi="1" ci="0" mb="0" cb="0" /><counter type="INSTRUCTION" missed="2" covered="3" /><counter type="LINE" missed="2" covered="3" /><counter type="METHOD" missed="0" covered="2" /><counter type="CLASS" missed="0" covered="1" /></sourcefile><counter type="INSTRUCTION" missed="2" covered="3" /><counter type="LINE" missed="2" covered="3" /><counter type="METHOD" missed="0" covered="2" /><counter type="CLASS" missed="0" covered="1" /></package><counter type="INSTRUCTION" missed="2" covered="3" /><counter type="LINE" missed="2" covered="3" /><counter type="METHOD" missed="0" covered="2" /><counter type="CLASS" missed="0" covered="1" /></report>
```

The command that I'm running is: 

```
Invoke-Pester .\CoverageTest.Tests.ps1 -CodeCoverage .\CoverageTest.ps1
```
And the output in the console is

```

WARNING: You are using Legacy parameter set that adapts Pester 5 syntax to Pester 4 syntax. This parameter set is deprecated, and does not work 100%. The -Strict and -PesterOption parameters are ignored, and providing advanced configuration to -Path (-Script), and -CodeCoverage via a hash table does not work. Please refer to https://github.com/pester/Pester/releases/tag/5.0.1#legacy-parameter-set for more information.

Starting discovery in 1 files.
Discovery finished in 34ms.
[+] C:\Users\<username>\Documents\Projects\pester\CoverageTest.Tests.ps1 170ms (9ms|128ms)
Tests completed in 172ms
Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 0
```

I've also tried using a pester configuration variable

```powershell
$pesterConfig = [PesterConfiguration]@{ 
    Run =@{
        path = './CoverageTest.Tests.ps1'
    } 
    CodeCoverage =@{
        enabled = $true
        path = './CoverageTest.ps1'
    }
}

Invoke-Pester -Configuration $pesterConfig
```

And the output of that is

```


Starting discovery in 1 files.
Discovery finished in 17ms.
[+] C:\Users\<username>\Documents\Projects\pester\CoverageTest.Tests.ps1 156ms (9ms|133ms)
Tests completed in 159ms
Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 0
```

Thanks!

**Comment by nohwnd** [comment] 2021-03-07 20:01
Yeah that does not work in 5.1, working on CC in 5.2. The latest 5.2.0-alpha1 has it, the next one will add a  $script:PesterPreference.codecoverage.CoveragePercentTarget = 75 option to print green message when the target is met, or red when not, instead of red when even a single command is not covered.

**Comment by nohwnd** [comment] 2021-03-07 20:03
Duplicate of #1625.

**Closed by nohwnd** 2021-03-07 20:03 UTC
