### ISSUE TITLE
.NET Framework 4.8 being installed seems to break Pester module

### ISSUE THREAD

**Issue by brettjacobson** [pester/Pester#1375] opened 2019-09-25 15:47 UTC
## 1. General summary of the issue

Installing and Importing Pester module after installing .NET Framework 4.8, causes `Invoke-Pester` to fail.

## 2. Describe Your Environment

I'm doing this Pester install into a Windows container, but I've verified that `Invoke-Pester` works fine if I do it before the .NET 4.8 install (manually), but that sequence is not viable in our automation.

```
Pester version     : 4.9.0 C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psd1
PowerShell version : 5.1.17763.592
OS version         : Microsoft Windows NT 10.0.17763.0
```

## 3. Expected Behavior

The `Invoke-Pester` invocation does not explode.

## 4.Current Behavior

```
PS C:\> Invoke-Pester
Unable to find type [Pester.OutputTypes].
At C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psm1:1054 char:9
+         [Pester.OutputTypes]$Show = 'All'
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Pester.OutputTypes:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

NOTE: supplying any number of parameter values to `Invoke-Pester` changes nothing.

## 6. Context

We are using Pester to execute "integration" tests to verify our containers were built to our specifications.  Thus, I cannot install/invoke pester prior to .NET Framework 4.8 being installed (since the containers purpose is to have the latest Visual Studio 2017 Build Tools installed, which installs .NET 4.8).  So we can no longer run our integration tests like we were doing with VS2017 install from a few weeks ago (which did not yet include .NET Framework 4.8).

**Comment by nohwnd** [comment] 2019-09-26 08:43
@brettjacobson thank you for reporting this. Could you provide a way to reproduce this please? For example the dockerfile or at least a base image and some steps you are doing so I can debug the problem. 🙂

**Comment by brettjacobson** [comment] 2019-09-27 14:54
@nohwnd I've found something very interesting (yet still inexplicable). It appears the problem is caused by using *chocolatey* to install .NET Framework 4.8.  If I download the installer directly and run it without using chocolatey, the problem does not present itself.

here is a dockerfile that uses chocolatey, and demonstrates the probem:
```dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:10.0.17763.737

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; $VerbosePreference='SilentlyContinue';"]
WORKDIR /


RUN Write-Host 'Fixing up PowerShellGet...'; `
	[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; `
	Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
	Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; `
	Write-Host 'Installing chocolatey...'; `
	Set-ExecutionPolicy Bypass -Scope Process -Force; `
	iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

RUN Write-Host 'Install other things (Visual Studio Build Tools) via chocolatey...'; `
	choco install --confirm --no-progress --name visualstudio2017buildtools --version 15.9.16.0 --package-parameters "--wait --quiet --norestart --nocache --noUpdateInstaller --includeRecommended --add Microsoft.VisualStudio.Workload.WebBuildTools"; `
	Write-Host 'Do pester things...'; `
	Install-Module -Name Pester -RequiredVersion 4.9.0 -SkipPublisherCheck; `
	Import-Module -Name Pester -Verbose; `
    Set-Location -Path $Env:USERPROFILE; `
    Invoke-Pester -Tags 'doesnotmatter';

ENTRYPOINT ["powershell"]
CMD ["-NoLogo", "-ExecutionPolicy", "Bypass"]
```
I checked the dependent pieces for the dotnetfx package, and they did not seem to cause the problem.

here is a dockerfile that does not use chocolatey to install .NET 4.8, and it is okay:
```dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:10.0.17763.737

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; $VerbosePreference='SilentlyContinue';"]
WORKDIR /

RUN Write-Host 'Fixing up PowerShellGet...'; `
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;

RUN Write-Host 'Downloading netfx...'; `
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; `
    Invoke-WebRequest -Uri 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe' -OutFile LatestVersionOfDotNet.exe; `
    Write-Host 'Installing netfx...'; `
    ./LatestVersionOfDotNet.exe /quiet /norestart;

RUN Write-Host 'Doing Pester things...'; `
    Install-Module -Name Pester -RequiredVersion 4.9.0 -SkipPublisherCheck -Verbose; `
    Import-Module -Name Pester -Verbose; `
    Set-Location -Path $Env:USERPROFILE; `
    Invoke-Pester -Tags 'doesnotmatter';

ENTRYPOINT ["powershell"]
CMD ["-NoLogo", "-ExecutionPolicy", "Bypass"]
```

I think for now I am going to have to try and install .NET 4.8 without chocolatey, and hope that the visual studio choco package respects that it is already installed.

**Comment by brettjacobson** [comment] 2019-09-27 15:15
Unfortunately, the potential workaround (pre-installing .NET 4.8 via the direct download) does not seem to resolve the problem.  Evidently the choco package for dotnetfx 4.8 still does whatever it does that seems to break Pester.

This dockerfile demonstrates that this workaround does not suffice :(

```dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:10.0.17763.737

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; $VerbosePreference='SilentlyContinue';"]
WORKDIR /


RUN Write-Host 'Fixing up PowerShellGet...'; `
	[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; `
	Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
	Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; `
	Write-Host 'Installing chocolatey...'; `
	Set-ExecutionPolicy Bypass -Scope Process -Force; `
	iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));

RUN Write-Host 'Downloading netfx...'; `
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; `
    Invoke-WebRequest -Uri 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe' -OutFile LatestVersionOfDotNet.exe; `
    Write-Host 'Installing netfx...'; `
    ./LatestVersionOfDotNet.exe /quiet /norestart;

RUN Write-Host 'Install other things via chocolatey...'; `
	choco install --confirm --no-progress --name dotnetfx --version 4.8.0.0; `
	Write-Host 'Do pester things...'; `
	Install-Module -Name Pester -RequiredVersion 4.9.0 -SkipPublisherCheck; `
	Import-Module -Name Pester -Verbose; `
    Set-Location -Path $Env:USERPROFILE; `
    Invoke-Pester -Tags 'doesnotmatter';

ENTRYPOINT ["powershell"]
CMD ["-NoLogo", "-ExecutionPolicy", "Bypass"]
```

The choco install of dotnetfx will report "WARNING: Microsoft .NET Framework 4.8 has been installed, but a reboot......." but it still "broke" Pester somehow.

Since we use the `visualstudio2017buildtools` chocolatey package, it is forcing the use of the dotnetfx 4.8 choco package, thus we are facing this problem.

**Comment by brettjacobson** [comment] 2019-09-27 15:16
Here is another error message that shows up when Importing Pester:

```text
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\Pester\4.9.0\Functions\Gherkin.types.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module Pester.
VERBOSE: Loading module from path 'C:\Program
Files\WindowsPowerShell\Modules\Pester\4.9.0\Pester.psm1'.
Add-Type : (0) : Required file 'alink.dll' could not be found
(1) :     namespace Pester
At C:\Program
Files\WindowsPowerShell\Modules\Pester\4.9.0\Functions\SetupTeardown.ps1:300
char:1
+ & $SafeCommands['Add-Type'] -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:
   AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.
   AddTypeCommand
```

**Comment by brettjacobson** [comment] 2019-10-01 13:48
@nohwnd have you had a chance to at least verify this is a real problem?

**Comment by nohwnd** [comment] 2019-10-01 14:23
I hopefully will have time this weekend, I only have Windows at home, and in a VM I cannot run docker.

**Comment by brettjacobson** [comment] 2020-03-05 04:58
I've recently circled back around, and this problem is still plaguing me :(  Have tested with latest Pester, as well.

**Comment by nohwnd** [comment] 2021-05-21 21:23
@brettjacobson still a problem another year later? :/

**Comment by fflaten** [comment] 2021-05-23 21:03
Able to reproduce. Closing issue as this is external to Pester. `Add-Type` in PowerShell itself is broken due to the missing `alink.dll` assembly. Can't even import a simple class using c#. Didn't work to run pester in a new layer neither.

**Workaround:** Install dotnetfx 4.7.2 (vsbuildtool dependency is 4.6.2 or above) as suggested in jberezanski/ChocolateyPackages#73. Confirmed working, ex:

```dockerfile
RUN Write-Host 'Install other things (Visual Studio Build Tools) via chocolatey...'; `
	choco install --confirm --no-progress --name dotnetfx --version 4.7.2.20180712;`
	choco install --confirm --no-progress --name visualstudio2017buildtools --version 15.9.16.0 --package-parameters "--wait --quiet --norestart --nocache --noUpdateInstaller --includeRecommended --add Microsoft.VisualStudio.Workload.WebBuildTools"; `
	exit 0
```

_(The `exit 0` is used to ignore WebBuildTools install error - that's probably fixed if you try a newer visualstudio2017buildtools package)_

**Closed by fflaten** 2021-05-23 21:03 UTC
Labels: Bug - external to Pester
