### ISSUE TITLE
Improvements to the progress reporting

### ISSUE THREAD

**Issue by theficus** [pester/Pester#373] opened 2015-06-19 19:05 UTC
The addition of adding a progress indicator when running a unit test is great. I have some suggestions to make it even better:

* Remove the "insert blank lines" code. This is really an implementation detail of the PSHost and just looks silly most of the time. I don't think I've seen anything else that uses the progress reporting that does this.

* Show a progress indicator when running BeforeEach/AfterEach/BeforeAll/AfterAll. Ideally when BeforeEach/AfterEach is run, it shows the test name. BeforeAll/AfterAll could show the describe name.

**Comment by Remco-74** [comment] 2015-06-24 20:46
It would be very nice to update the progressbar incrementally (moving from left to right) as well.

**Comment by theficus** [comment] 2015-06-25 02:23
Unfortunately PowerShell doesn't support indeterminate progress bars so there's really no good way to get it to move. Either way it's an improvement to know what's running as its running. It can just be made even better. :)

**Comment by Remco-74** [comment] 2015-07-01 08:04
This can be fixed with a single line of code. I have written a patch for this, but i'm not sure to how to submit this. What is the best way to do that?

**Comment by Remco-74** [comment] 2015-07-04 10:30
I've made a pull request to improve the progress reporting, but it fails during build (since i didn't add any new tests).

http://teamcity.codebetter.com/viewLog.html?buildId=194548&buildTypeId=Pester_TestPullRequests&guest=1

I'm not quite sure how to write a test that invokes [Invoke-Pester] itself. I didn't find other testcases that do that as well. 

How to proceed from here?

**Comment by dlwyatt** [comment] 2015-07-04 13:53
The problem isn't that you didn't add any new tests.  The build log contains this error:

```
[Step 1/1] Z:\Builds\temp\buildTmp\powershell6628862289246688128.ps1 : The variable '$cnt'
[06:25:57][Step 1/1]  cannot be retrieved because it has not been set.
[06:25:57][Step 1/1]     + CategoryInfo          : InvalidOperation: (cnt:Token) [Write-Error], Run 
[06:25:57][Step 1/1]    timeException
[06:25:57][Step 1/1]     + FullyQualifiedErrorId : VariableIsUndefined,powershell662886228924668812 
[06:25:57][Step 1/1]    8.ps1
[06:25:57][Step 1/1]  
[06:25:57][Step 1/1] Process exited with code 1
[06:25:59][Step 1/1] ##teamcity[buildStatisticValue key='buildStageDuration:buildStepRUNNER_1278' value='2169.0']
[06:25:59][Step 1/1] Step PowerShell v2 Tests (Powershell) failed
```

Keep in mind that Pester needs to remain compatible with `Set-StrictMode -Version Latest`, and all versions of PowerShell from v2 onward.  :)

**Comment by Remco-74** [comment] 2015-07-04 15:56
Ah, ok. That makes sense. I will prepare a new simple PR with only the progress fix (leaving out the timing issue).

**Comment by Remco-74** [comment] 2015-07-04 16:22
I just made this Pull Request:
https://github.com/pester/Pester/pull/382

**Closed** 2015-07-14 14:51 UTC

**Comment by Remco-74** [comment] 2015-07-14 22:34
Why was this issue closed?

**Comment by dlwyatt** [comment] 2015-07-15 00:33
I thought the discussion in the pull request was done, but if you've got more to add, feel free to open it up again.  :)

**Comment by theficus** [comment] 2015-07-24 17:38
I just checked in the latest bits and this issue doesn't appear to have been fixed yet.
