### ISSUE TITLE
Context block throws "New-PSDrive : A drive with the name 'TestDrive' already exists."

### ISSUE THREAD

**Issue by ChrisLynchHPE** [pester/Pester#1070] opened 2018-07-01 04:20 UTC
## 1. Provide a general summary of the issue in the Title above

During unit test execution through AppVeyor, Pester will throw an error `New-PSDrive : A drive with the name 'TestDrive' already exists.`  Here are two examples of the output from two independently ran builds:
* [Example1](https://ci.appveyor.com/project/ChrisLynchHPE/posh-hponeview-34esg#L202)
* [Example2](https://ci.appveyor.com/project/ChrisLynchHPE/posh-hponeview-0fpb0/build/4.10.4#L414)

## 2. Describe Your Environment

Operating System, Pester version and PowerShell version:

```powershell
Pester version     : 4.4.0 4.3.1 4.0.3 4.0.2 3.4.0 C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.0\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.3\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.2\Pester.psd1 C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Pester.psd1
PowerShell version : 5.1.16299.522
OS version         : Microsoft Windows NT 10.0.16299.0
```
I am using Pester 4.4.0-Beta, which this can be reproduced with Pester 4.3.1.

## 3. Expected Behavior

I have no need for a Test-Drive in most of the `Context` blocks I have written.

## 4.Current Behavior

I provided links to the AppVeyor desktop output.  The code in question is:

```powershell
Describe "Firmware Baseline Management" -Tag All, Baseline, ApplianceBase {

    BeforeAll {

        if (-not $ConnectedSessions) {

            { $Connection1 = Connect-HPOVMgmt -Hostname $Appliance1 -Credential $AppliancePSCredential -LoginAcknowledge } | Should -Not -Throw

        }

        if (-not ($ConnectedSessions | Where-Object Name -eq $Appliance1).Default) {

            ($ConnectedSessions | Where-Object Name -eq $Appliance1) | Set-HPOVApplianceDefaultConnection

        }

        Microsoft.PowerShell.Utility\write-host ('Default Appliance Connection: {0}' -f ($ConnectedSessions | Where-Object Default ).Name) -ForegroundColor Yellow

        $ExistingExternalRepo = (sr "/rest/repositories?query=repositoryType EQ 'FirmwareExternalRepo'").members

        if ($null -ne $ExistingExternalRepo) {

            $ExistingExternalRepo | % {

                Microsoft.PowerShell.Utility\write-host ('Removing existing external repo: {0}' -f $_.name) -ForegroundColor Yellow

                Send-HPOVRequest -Uri ($_.uri + "?force=true") -Method DELETE | Wait-HPOVTaskComplete | Out-Null

            }           

        }

    }

    AfterAll {

        If ($ConnectedSessions) {

            { Disconnect-HPOVMgmt $ConnectedSessions -ErrorAction Stop } | Should -Not -Throw

        }

    }

    Context "Validate Default Baseline resource" {
    
        It "Will validate Default Baseline exists" {
    
            { $Script:DefaultBaselineObject = Get-HPOVBaseline -File $ExistingBaselineName -ErrorAction Stop } | Should -Not -Throw
            $DefaultBaselineObject | Should -Not -BeNullOrEmpty
            $DefaultBaselineObject.category | Should -Be 'firmware-drivers'
    
        }
    
    }

    Context "Upload Support Pack for ProLiant" {

        It "Will attempt to upload SPP Baseline using invalid file" {

            $ExpectedExceptionMessage = "Cannot validate argument on parameter 'File'."
            
            { Add-HPOVBaseline -File Foo.iso } | Should -Throw $ExpectedExceptionMessage

        }

        It "Will upload SPP Baseline" {

            { Add-HPOVBaseline -File $SppFile -ErrorAction Stop } | Should -Not -Throw

        }

        It "Will validate SPP Baseline exists using -IsoFileName alias" {

            { $Script:BaselineObject = Get-HPOVBaseline -IsoFileName $SppFile.name -ErrorAction Stop } | Should -Not -Throw
            (Measure-Object -InputObject $BaselineObject).Count | Should -BeExactly 1
            $BaselineObject.isoFileName | Should -BeExactly $SppFile.Name

        }

        It "Will attempt to retrieve invalid Baseline Filename" {

            $ExpectedExceptionMessage = "The Baseline resource name 'foo.iso' was not found on '{0}' appliance." -f $Appliance1
            
            { Get-HPOVBaseline -File foo.iso -ErrorAction Stop } | Should -Throw $ExpectedExceptionMessage
        
        }

        It "Will attempt upload same SPP File and throw error" {

            $ExpectedExceptionMessage = "The Baseline '{0}' is already present on the appliance" -f $SppFile.Name
            
            { Add-HPOVBaseline -File $SppFile -ErrorAction Stop } | Should -Throw $ExpectedExceptionMessage

        }

    }

    Context "Custom Baseline Management" {
    
        It "Will attempt to create a custom baseline with invalid baseline object name" {
    
            #$ExpectedExceptionMessage = "The Baseline name 'foo' was not found."
            
            { New-HPOVCustombaseline -BaselineName InvalidBaseline -SourceBaseline foo -Hotfixes bar.scexe } | Should -Throw
    
        }

        It "Will attempt to create a custom baseline with invalid hotfix object" {

            $SourceBaseline = Get-HPOVBaseline -File $ExistingBaselineName
        
            $ExpectedExceptionMessage = "The provided Hotfix 'bar.scexe' was not found."
            
            { New-HPOVCustomBaseline -BaselineName InvalidBaseline -SourceBaseline $SourceBaseline -hotfixes bar.scexe } | Should -Throw $ExpectedExceptionMessage
        
        }

        It "Will upload hotfix '$($HotfixToUpload.Name)' to appliance" {
        
            { $Script:HotfixUploadResults = Add-HPOVBaseline -File $HotfixToUpload } | Should -Not -Throw
            $HotfixUploadResults | Should -Not -BeNullOrEmpty
            $HotfixUploadResults.category | Should -Be 'tasks'

            if ($HotfixUploadResults.taskState -ne "Completed") {

                DisplayTaskError $HotfixUploadResults

            }

            $HotfixUploadResults.taskState | Should -Be Completed
        
        }

        It "Will validate hotfix was uploaded using -HotfixesOnly parameter" {
        
            { $Script:Results = Get-HPOVBaseline -HotfixesOnly | Where-Object uuid -eq $HotfixToUpload.Name.Replace('.scexe', $null).Replace('.exe', $null).Replace('.rpm',$null).Replace('.','_') } | Should -Not -Throw

            $Results | Should -Not -BeNullOrEmpty
            $Results.bundleType | Should -Be Hotfix
            $Results.bundleSize | Should -BeGreaterThan 0
        
        }

        It "Will create custom baseline '$CustomBaselineName' using '$ExistingBaselineName' and '$($HotfixToUpload.Name)' [#148]" {
        
            { $Script:SourceBaseline = Get-HPOVBaseline -File $ExistingBaselineName -ErrorAction Stop } | Should -Not -Throw
            { $Script:Hotfix1 = Get-HPOVBaseline -File $HotfixtoUpload.Name -ErrorAction Stop } | Should -Not -Throw

            { $Script:CreateCustomBaselineResults = New-HPOVCustomBaseline -BaselineName $CustomBaselineName -SourceBaseline $SourceBaseline -Hotfixes $Hotfix1 } | Should -Not -Throw
            $CreateCustomBaselineResults | Should -Not -BeNullOrEmpty
            $CreateCustomBaselineResults.category | Should -Be 'tasks'

            if ($CreateCustomBaselineResults.taskState -ne "Completed") {

                DisplayTaskError $CreateCustomBaselineResults

            }

            $CreateCustomBaselineResults.taskState | Should -Be Completed
        
        }
    
    }

    Context "Manage External Repository" {

        It "Will validate Internal Repository exists" {

            { $Script:InternalRepository = Get-HPOVBaselineRepository -Type Internal -ErrorAction Stop } | Should -Not -Throw
            $InternalRepository | Should -Not -BeNullOrEmpty
            $InternalRepository.name | Should -Be Internal

        }

        It "Will add an external repository using HTTP protocol and anonymous auth" {

            $Params = @{

                Name      = $ExternalRepositoryName;
                Hostname  = $ExternalRepositoryHostname;
                Directory = $ExternalAnonymousRepoDirectory;
                Http      = $True;

            }

            { $Script:Results = New-HPOVExternalRepository @Params } | Should -Not -Throw

            $Results | Should -Not -BeNullOrEmpty
            $Results.category | Should -Be 'tasks'

            # Implement workaround for appliance "refresh race condition"
            if ($Results.taskState -ne "Completed" -and $Results.errorCode -ne 'REPOSITORY_RFRESH_EXCEPTION') {

                DisplayTaskError $Results

            }

            if ($Results.errorCode -eq 'REPOSITORY_RFRESH_EXCEPTION')
            {
            
                $true | Should -BeTrue
            
            }

            else
            {
            
                $Results.taskState | Should -Be Completed
            
            }            

        }

        It "Will refresh the external repository" {
        
            { $Script:Results = Get-HPOVBaselineRepository -Type External | Update-HPOVExternalRepository -Confirm:$False } | Should -Not -Throw

            if ($Results.taskState -ne "Completed") {

                DisplayTaskError $Results

            }

            $Results.taskState | Should -Be Completed
        
        }

        It "Will remove added external repository" {

            { $Script:RemoveResults = Get-HPOVBaselineRepository -Name $ExternalRepositoryName -ErrorAction Stop | Remove-HPOVExternalRepository -Confirm:$false } | Should -Not -Throw

            
            $RemoveResults | Should -Not -BeNullOrEmpty
            $RemoveResults.category | Should -Be 'tasks'

            if ($RemoveResults.taskState -ne "Completed") {

                DisplayTaskError $RemoveResults

            }

            $RemoveResults.taskState | Should -Be Completed

        }
        
        It "Will add an external repository using HTTPS protocol and standard auth (no PSCredential)" {

            $Script:ShouldSkipExtRepoRemove = $false

            $TrapableExceptionMessage = 'Unable to access files on external repository due to internal error.'

            $Params = @{

                Name        = $ExternalRepositoryName;
                Hostname    = $ExternalRepositoryHostname;
                Directory   = $ExternalRepositoryDirectory;
                Username    = $ExternalRepositoryUsername;
                Password    = $ExternalRepositoryPassword;
                Certificate = $ExternalRepositoryBase64Cert

            }

            # Implement as a workaround for appliance internal error
            Try
            {
            
                $Script:Results = New-HPOVExternalRepository @Params

                $Results | Should -Not -BeNullOrEmpty
                $Results.category | Should -Be 'tasks'

                if ($Results.taskState -ne "Completed") {

                    DisplayTaskError $Results

                }

                $Results.taskState | Should -Be Completed
            
            }
            
            Catch
            {

                $_CaughtError = $_.PSObject.Copy()
            
                if ($_.Exception -match $TrapableExceptionMessage)
                {

                    $ShouldSkipExtRepoRemove = $true

                }

                else
                {

                    { Throw $_CaughtError } | Should -Not -Throw

                }
            
            }

        }

        It "Will remove added external repository" -Skip:$ShouldSkipExtRepoRemove {

            { $Script:RemoveResults = Get-HPOVBaselineRepository -Name $ExternalRepositoryName -ErrorAction Stop | Remove-HPOVExternalRepository -Confirm:$false } | Should -Not -Throw

            
            $RemoveResults | Should -Not -BeNullOrEmpty
            $RemoveResults.category | Should -Be 'tasks'

            if ($RemoveResults.taskState -ne "Completed") {

                DisplayTaskError $RemoveResults

            }

            $RemoveResults.taskState | Should -Be Completed

        }

        It "Will add an external repository using HTTPS protocol and standard auth (PSCredential)" {

            $Params = @{

                Name        = $ExternalRepositoryName;
                Hostname    = $ExternalRepositoryHostname;
                Directory   = $ExternalRepositoryDirectory;
                Credential  = $ExternalRepositoryPSCredential;
                Certificate = $ExternalRepositoryBase64Cert

            }

            { $Script:Results = New-HPOVExternalRepository @Params } | Should -Not -Throw

            $Results | Should -Not -BeNullOrEmpty
            $Results.category | Should -Be 'tasks'

            if ($Results.taskState -ne "Completed") {

                DisplayTaskError $Results

            }

            $Results.taskState | Should -Be Completed

        }

        It "Will modify the existing external repository name with an updated value (PSCredential)" -Skip {

            $NewName = $ExternalRepositoryName + "_Updated"

            $Params = @{

                Name       = $NewName;
                Credential = $ExternalRepositoryPSCredential

            }

            { $Script:RemoveResults = Get-HPOVBaselineRepository -Name $ExternalRepositoryName -ErrorAction Stop | Set-HPOVExternalRepository @Params -Confirm:$false } | Should -Not -Throw

            
            $RemoveResults | Should -Not -BeNullOrEmpty
            $RemoveResults.category | Should -Be 'tasks'

            if ($RemoveResults.taskState -ne "Completed") {

                DisplayTaskError $RemoveResults

            }

            $RemoveResults.taskState | Should -Be Completed

        }

        It "Will validate repository resource name was updated to new value" -Skip {

            $NewName = $ExternalRepositoryName + "_Updated"

            { Get-HPOVBaselineRepository -Name $NewName -ErrorAction Stop } | Should -Not -Throw

        }

    }

    Context "Remove Baselines" {
    
        It "Will remove Custom Baseline" {

            { Get-HPOVBaseline -File $CustomBaselineName -ErrorAction Stop | Remove-HPOVBaseline -confirm:$false | Wait-HPOVTaskComplete } | Should -Not -Throw

        }

        It "Will remove Hotfix resource" {

            { Get-HPOVBaseline -File $HotfixToUpload.Name -ErrorAction Stop | Remove-HPOVBaseline -confirm:$false | Wait-HPOVTaskComplete } | Should -Not -Throw

        }
        
        It "Will remove Baseline resource" {

            { Get-HPOVBaseline -File $SppFile.Name -ErrorAction Stop | Remove-HPOVBaseline -confirm:$false | Wait-HPOVTaskComplete } | Should -Not -Throw

        }

        It "Will remove added external repository" {


            { $Script:RemoveResults = Get-HPOVBaselineRepository -Type External -ErrorAction Stop | Remove-HPOVExternalRepository -Force -Confirm:$false } | Should -Not -Throw

            
            $RemoveResults | Should -Not -BeNullOrEmpty
            $RemoveResults.category | Should -Be 'tasks'

            if ($RemoveResults.taskState -ne "Completed") {

                DisplayTaskError $RemoveResults

            }

            $RemoveResults.taskState | Should -Be Completed

        }
    
    }

}```

**Comment by mikeclayton** [comment] 2018-07-02 13:08
I can reproduce this error with the following pathological test script:

```powershell
Describe "TestDrive Exception" {

    Context "context one" {
        It "delete tempdrive root folder" {
            $drive = Get-PSDrive "TestDrive";
            $null = remove-item $drive.Root;
            $true | should be $true;
        }
    }

    Context "context two" {
        It "Will fail with testdrive exception" {
            $true | should be $true;
        }
    }

}
```

output:

```text
C:\src\scratch\pester\issue-1070>powershell .\issue-1070.ps1
Executing all tests in '.\pathological.Tests.ps1'

Executing script .\pathological.Tests.ps1

  Describing TestDrive Exception

    Context context one
      [+] delete tempdrive root folder folder 564ms

    Context context two
New-PSDrive : A drive with the name 'TestDrive' already exists.
At C:\src\scratch\pester\Pester.4.3.1\tools\Functions\TestDrive.ps1:24 char:9
+         & $SafeCommands['New-PSDrive'] -Name $DriveName -PSProvider F ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (TestDrive:String) [New-PSDrive], SessionStateException
    + FullyQualifiedErrorId : DriveAlreadyExists,Microsoft.PowerShell.Commands.NewPSDriveCommand

      [+] Will fail with testdrive exception 193ms
    [-] Error occurred in Describe block 46ms
      ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
      at Remove-TestDrive, C:\src\scratch\pester\Pester.4.3.1\tools\Functions\TestDrive.ps1: line 130
      at DescribeImpl, C:\src\scratch\pester\Pester.4.3.1\tools\Functions\Describe.ps1: line 171
Tests completed in 804ms
Tests Passed: 2, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

Basically, if something running inside the tests deletes the filesystem folder underneath "TestDrive:" (or, e.g., the entire %temp% directory) the next set of tests will try to re-create the TestDrive again because it tests for the *root folder* existing, not the PSDrive itself.

Changing https://github.com/pester/Pester/blob/master/Functions/TestDrive.ps1#L20 to this instead:

```
    $testdrive = & $SafeCommands['Get-PSDrive'] -Name $DriveName -ErrorAction $script:IgnoreErrorPreference
    if ( $null -eq $testdrive )

```
solves the immediate issue, but then it hits other problems in Remove-TestDrive - i'm not sure if this also needs tweaking, or if the fix I suggested above just isn't a very good one :-)

**Comment by ChrisLynchHPE** [comment] 2018-07-02 16:44
So, I am not removing the `TestDrive` resource in my Pester tests.  I do use `Remove-Item` to delete specific files copied or stored on the `$TestDrive` location.  But those are in different `Context` blocks, as the script above is a root `Context` block in my unit test script.

**Comment by it-praktyk** [comment] 2018-07-02 19:32
Can you verify the behavior with the #1059 applied?

**Comment by mikeclayton** [comment] 2018-07-02 20:39
@ChrisLynchHPE - I've not used AppVeyor before - is it possible some other build or process in the same context (e.g. same VM / container) is running under the same user account and is intermittently deleting the contents of %temp% (normally resolves to ```C:\Users\<username>\AppData\Local\Temp```)?

The PowerShell "TestDrive:\" is a virtual drive mapped to a folder with a random guid under %temp% (e.g. ```C:\Users\<username>\AppData\Local\Temp\f55782d7-f3d7-4695-8851-1648ce51183f```, and if another process were to delete everything in ```C:\Users\<username>\AppData\Local\Temp``` while your tests were running it *could* cause the issue above.

It looks like this is because Pester calls ```Test-Path "TestDrive:\"``` to see whether the TestDrive already exists, rather than ```Get-PSDrive -Name "TestDrive"```. If Test-Path returns $false it tries to create the TestDrive with ```New-PSDrive -Name "TestDrive```, even if the PSDrive object already exists (which would explain the error you're seeing).

Apologies if this is something you already know - I only learnt it today by picking through the code (I'm not on the Pester dev team!).

**Comment by nohwnd** [comment] 2018-07-08 10:52
Just merged #1059 that is related to deleting the underlying folder. It throws error when the folder is not found, maybe it will help identifying what exactly is happening.

**Comment by nohwnd** [comment] 2018-12-16 19:02
Threre was also a weird bug where `Test-Path` on `(Get-PSDrive -name TestDrive).Root`  would return $false for the path, but `Get-PSDrive` on line above and below the `Test-Path` would return the drive... Can we still reproduce this?  We could test the drive by checking it exists, but that check is 2 times slower, so that's at least +10ms per block.

**Comment by ChrisLynchHPE** [comment] 2018-12-17 18:14
I have not seen this happen in quite a long time.  I am using 4.0.4 on my Windows 10 worker VM.  I think this issue can be closed.

**Comment by nohwnd** [comment] 2018-12-17 21:36
Ok.

**Closed by nohwnd** 2018-12-17 21:36 UTC
