### ISSUE TITLE
Add native ability to only display failed/passed tests

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#674] opened 2017-01-12 16:42 UTC
Rather than using -PassThru and building my own Invoke-Pester wrapper, it'd be nice to have a -Filter parameter on Invoke-Pester to limit to only failed tests.

**Comment by nohwnd** [comment] 2017-01-12 16:44
Are you after filtering what is printed to the screen? see https://github.com/pester/Pester/pull/647

**Comment by adbertram** [comment] 2017-01-12 16:45
Oh, nice! I wasn't aware of the Show parameter.

**Comment by adbertram** [comment] 2017-01-12 16:54
I don't see this available on 3.4.4. Is it an unreleased feature?

**Comment by nohwnd** [comment] 2017-01-12 17:49
Yes, it is not merged yet. I can merge it and release it as 3.4.5 today.


Jakub Jareš

.NET, Pester, PowerShell
t 00420603800578<tel:00420603800578>
e me@jakubjares.com<mailto:me@jakubjares.com>
t @nohwnd

12. 1. 2017 v 17:55, Adam Bertram <notifications@github.com<mailto:notifications@github.com>>:


I don't see this available on 3.4.4. Is it an unreleased feature?

**Comment by nohwnd** [comment] 2017-01-12 18:18
Duplicate of #647

**Closed by nohwnd** 2017-01-12 18:18 UTC
