### ISSUE TITLE
Feature suggestion: Invoke-Pester to take in results from previous run and only re-run failed tests

### ISSUE THREAD

**Issue by theficus** [pester/Pester#355] opened 2015-05-21 23:11 UTC
When I'm working on creating or modifying unit tests, especially Describe { } blocks with numerous It { } tests it's a pain to have to wait for all of the previously passing tests to run before it gets to the ones I'm interested in (the failing ones).

When running unit tests in Visual Studio, you have an option to "re-run failed tests". It would be extremely cool and useful if you could take a result from a previous Invoke-Pester run, feed that into Invoke-Pester and have it only re-run the tests that were not successful from a previous run. This would be a huge time saver when working on new test automation.

Example:

``` powershell
PS:\> $results = Invoke-Pester C:\Tests\MyTests.Tests.ps1 -PassThru
# blahblahblahblah
Tests completed in 999.99s
Passed: 16 Failed: 6 Skipped: 0 Pending: 0

# Re-run all failed tests from the previous run
PS:\> $results | Invoke-Pester

# Re-run any Failed or Skipped tests from the previous run
PS:\> $results | Invoke-Pester -Rerun ("Failed", "Skipped")

# Re-run any failed or skipped tests and use standard filtering mechanisms. This would require putting
# additional metadata into the TestResult object as it doesn't contain Tag information today.
PS:\> $results | Invoke-Pester -Rerun ("Failed", "Skipped") -ExcludeTag P3 -TestName FooBar

# Let's get really crazy here, and re-run and only run tests that have been added since the
# previous results were captured. All other standard filtering and what-not applies.
PS:\> Invoke-Pester C:\Tests\MyTests.Tests.ps1 -OnlyNewTests $results
```

It seems that the output results have a lot of untapped potential.

See also: #352

**Comment by dlwyatt** [comment] 2015-05-21 23:40
That's an interesting idea, though I'm not sure it would work for everyone.  Here are my initial thoughts:

- Most of the time spent in a test script is typically out in the Describe and Context blocks.  Your mileage may vary, of course, but a lot of the "Arrange" and "Act" phases tends to be done outside of an It block, and the "Assert" phase done inside It blocks, in the tests that I've written and seen so far.

- This means that to get the most benefit, we'd have to skip entire Describe or Context blocks if there are no tests that need to be re-run inside of them.  That's easy enough to do, but if a single test fails in those blocks, you're probably going to be taking up most of the time anyway (even if other It blocks are skipped.)

- This may not work well for everyone, depending on how your tests are written.  Tests may depend on variables populated by a previous test, for example, and if the previous test passed and is then skipped, the dependent test is always going to fail.

Anyhow, I don't think this will be hard to implement, but the benefit will depend a lot on how the test author structures their code.

**Comment by theficus** [comment] 2015-05-21 23:46
Yes, this would definitely depend on how scripts are authored. If you take an approach of keeping each It { } as atomic as possible this would work very well. If you have a lot of comingling, then yeah, this approach wouldn't work.

I tend to go with the MSTest/NUnit school of "every test should be considered its own scope unless you explicitly define something as being global outside of your test" approach and only define anything shared in BeforeAll or in my fixture before the first Describe block is hit. My idea would work well if you author your scripts this way, otherwise, yeah, it wouldn't work out so great. :)

**Comment by fourpastmidnight** [comment] 2019-01-18 17:56
We could take the approach that _cucumber_ takes, which is provide an option to output a rerun file. Then, on the next run, you could do something like `Invoke-Pester [other options] -Rerun rerun.txt`.

**Comment by nohwnd** [comment] 2019-01-18 22:41
Planned ( and almost implemented for v5)

**Comment by nohwnd** [comment] 2019-03-24 13:07
Closing this because it duplicate of #1161 and the basic ideas are already in the code.

**Closed by nohwnd** 2019-03-24 13:07 UTC
Labels: Feature
