### ISSUE TITLE
Errors running v5 examples from pester.dev/docs/usage/modules

### ISSUE THREAD

**Issue by rmbolger** [pester/Pester#1693] opened 2020-09-25 20:35 UTC
## 1. General summary of the issue

Trying out the current 5.0.4 release and testing the examples provided in https://pester.dev/docs/usage/modules but running into errors.

## 2. Describe Your Environment

Pester version     : 5.0.4 C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psd1
PowerShell version : 5.1.19041.1
OS version         : Microsoft Windows NT 10.0.19041.0
*(I've also tried testing in PS 7.0.3 as well)*

I've created a `Documents\WindowsPowerShell\Modules\MyModule\MyModule.psm1` file with the contents of the script module text from the doc page. I also made a copy in `Documents\PowerShell\Modules` for use with PS 7. I can successfully `Import-Module MyModule` and run the public `BuildIfChanged` function in both environments.

I created a `MyModule.Test1.ps1` file for the first example where the mocks are using `-ModuleName` and applied the fix from https://github.com/pester/docs/pull/59. I created a `MyModule.Test2.ps1` file for the second example where `InModuleScope` is used.

## 3. Expected Behavior

When running `Invoke-Pester -Path .\MyModule.Test1.ps1`, tests should run and succeed without errors.
When running `Invoke-Pester -Path .\MyModule.Test2.ps1`, tests should run and succeed without errors.

## 4.Current Behavior

When running `Invoke-Pester -Path .\MyModule.Test1.ps1`, I get the following output.

```
Starting discovery in 1 files.
Discovery finished in 545ms.
[-] BuildIfChanged.When there are Changes.returns the next version number 259ms (257ms|3ms)
 Expected 1.2, but got $null.
 at $result | Should -Be 1.2, D:\temp\MyModule.Test1.ps1:21
 at <ScriptBlock>, D:\temp\MyModule.Test1.ps1:21
Tests completed in 3.13s
Tests Passed: 2, Failed: 1, Skipped: 0 NotRun: 0
```

When running `Invoke-Pester -Path .\MyModule.Test2.ps1`, I get the following output.

```
Starting discovery in 1 files.
a build was run for version: 5
Discovery finished in 47ms.
[-] Unit testing the module's internal Build function:.Outputs the correct message 14ms (13ms|1ms)
 Expected Write-Host to be called at least 1 times but was called 0 times
 at Should -Invoke @__params__p, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psm1:12004

Tests completed in 104ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

## 5. Possible Solution

I'm guessing this is an artifact from the doc not being updated for v5. But I'm struggling to understand how it needs to be updated.

## 6. Context

Ultimately, I'm just looking for v5 guidance on testing script modules including both public and internal functions.

**Comment by fflaten** [comment] 2020-09-26 22:10
Try the updated tests below. All setup moved inside `Before*` as per v5 requirements and updated deprecated Assert-* methods to `Should *` equivalents. See README.md for 

MyModule.Test1.ps1

```
BeforeAll {
    Import-Module $PSScriptRoot/MyModule.psm1
}

Describe "BuildIfChanged" {
    Context "When there are Changes" {

        BeforeAll {
            Mock -ModuleName MyModule Get-Version { return 1.1 }
            Mock -ModuleName MyModule Get-NextVersion { return 1.2 }

            # Just for giggles, we'll also mock Write-Host here, to demonstrate that you can
            # mock calls to commands other than functions defined within the same module.
            Mock -ModuleName MyModule Write-Host {} -Verifiable -ParameterFilter {
                $Object -eq 'a build was run for version: 1.2'
            }

            $result = BuildIfChanged
        }

        It "Builds the next version and calls Write-Host" {
            Should -InvokeVerifiable
        }

        It "returns the next version number" {
            $result | Should -Be 1.2
        }
    }

    Context "When there are no Changes" {

        BeforeAll {
            Mock -ModuleName MyModule Get-Version { return 1.1 }
            Mock -ModuleName MyModule Get-NextVersion { return 1.1 }
            Mock -ModuleName MyModule Build { }

            $result = BuildIfChanged
        }

        It "Should not build the next version" {
            #-Scope Context since BuildIfChanged is called in BeforeAll. Remove if $result = BuildIfChanged is called inside It
            Should -Invoke Build -ModuleName MyModule -Times 0 -Scope Context -ParameterFilter {
                $version -eq 1.2
            }
        }
    }
}
```

MyModule.Test2.ps1 should probably look something like this, however I'm having problems making the ParameterFilter work. @nohwnd Any ideas? 

```
BeforeAll {
    Import-Module $PSScriptRoot/MyModule.psm1
}

Describe "Unit testing the module's internal Build function:" {

    It 'Outputs the correct message' {

        InModuleScope MyModule {
            $testVersion = 5.0
            Mock Write-Host { }

            Build $testVersion

            Should -Invoke Write-Host -ParameterFilter {
                $Object -eq "a build was run for version: $testVersion"
            }

        }
    }

}
```

Works without the filter, but fails with it - even if I replace $testVersion with "5" hard-coded. Any tips @nohwnd ?

```
Mock: Found the command Write-Host in the caller scope and it resolved to PesterMock_fc62c391-539e-4089-8937-cc9e4339835c. 
Mock: Running mock filter { 
                $Object -eq "a build was run for version: 5"
             } with context: Msg = a build was run for version: 5, Message = a build was run for version: 5, Object = a build was run for version: 5. 
Mock: Mock filter did not pass. 
  [-] Outputs the correct message 39ms (35ms|4ms)
   Expected Write-Host to be called at least 1 times but was called 0 times
   at Should -Invoke Write-Host -ParameterFilter {, /workspaces/Pester/SampleProject/MyModule.Test2.ps1:15
   at <ScriptBlock>, /workspaces/Pester/SampleProject/MyModule.Test2.ps1:15
```

**Comment by rmbolger** [comment] 2020-09-26 23:45
Awesome! Thanks for the fixes in the Test1 example. Interestingly, For Test2, I'm getting different results than you and they're inconsistent. If I open a fresh PowerShell session and only run Test2, it works (repeatedly). If I run Test1 in that same session, it seems to break Test2. When I run Test2 again, I get this output.

```
Starting discovery in 1 files.
Discovery finished in 5ms.
[-] Unit testing the module's internal Build function:.Outputs the correct message 87ms (85ms|2ms)
 Expected Write-Host to be called at least 1 times but was called 0 times
 at Should -Invoke Write-Host -ParameterFilter {, D:\temp\MyModule.Test2.ps1:15
 at <ScriptBlock>, D:\temp\MyModule.Test2.ps1:15
Tests completed in 195ms
Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 0
```

**Comment by fflaten** [comment] 2020-09-27 12:58
You're right. Test2.ps1 works as it should by itself.

What I noticed is that while running Test1.ps1, the Diagnostic output says that it removes the Mocks in the end, but they are still left inside the Module scope of MyModule. There are no leftovers from Test2.ps1, however they are very different due to usage of InModuleScope. I'm not very experienced with mocks, but AFAIK you shouldn't need to manually cleanup Mocks created inside BeforeAll. Need @nohwnd to confirm if this is a issue during mock cleanup or a rookie mistake 🙂 .

Tested with Pester 5.0.5-beta1

```
# Run test1.ps1 in a newly opened PowerShell session
PS /workspaces/Pester> Invoke-Pester -Path ./SampleProject/MyModule.Test1.ps1 -Output Diagnostic
..
   [+] Builds the next version and calls Write-Host 62ms (40ms|22ms)
   [+] returns the next version number 32ms (27ms|6ms)
Mock: Removing function PesterMock_62932893-9ffe-47ba-9fd8-72f460e4dfaa and aliases Get-Version, MyModule\Get-Version for Get-Version. 
Mock: Removing function PesterMock_e4fb0f70-3315-4be8-99b2-0856f4ce01b1 and aliases Get-NextVersion, MyModule\Get-NextVersion for Get-NextVersion. 
Mock: Removing function PesterMock_c9484003-10dc-469d-bcbb-d008c01407e1 and aliases Write-Host, Microsoft.PowerShell.Utility\Write-Host for Write-Host. 
 Context When there are no Changes
..
Mock: Found the command Build in a different module and it resolved to PesterMock_53a4c1dd-294b-4432-8dc9-1127d7591bcb. 
   [+] Should not build the next version 50ms (44ms|5ms)
Mock: Removing function PesterMock_53a4c1dd-294b-4432-8dc9-1127d7591bcb and aliases Build, MyModule\Build for Build. 
Tests completed in 1.06s
Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 0

# Check for mocks in module scope
PS /workspaces/Pester> & (Get-Module MyModule) { Get-Command PesterMock_* }                     

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        PesterMock_53a4c1dd-294b-4432-8dc9-1127d7591bcb               
Function        PesterMock_62932893-9ffe-47ba-9fd8-72f460e4dfaa               
Function        PesterMock_c9484003-10dc-469d-bcbb-d008c01407e1               
Function        PesterMock_e4fb0f70-3315-4be8-99b2-0856f4ce01b1               

PS /workspaces/Pester> & (Get-Module MyModule) { Get-Alias "*Get-Version","*Get-NextVersion","*Write-Host","*Build" | Ft CommandType, Name, Version, Source, ResolvedCommandName }


CommandType Name                                    Version Source   ResolvedCommandName
----------- ----                                    ------- ------   -------------------
      Alias Get-Version                             0.0     MyModule PesterMock_62932893-9ffe-47ba-9fd8-72f460e4dfaa
      Alias MyModule\Get-Version                    0.0     MyModule PesterMock_62932893-9ffe-47ba-9fd8-72f460e4dfaa
      Alias Get-NextVersion                         0.0     MyModule PesterMock_e4fb0f70-3315-4be8-99b2-0856f4ce01b1
      Alias MyModule\Get-NextVersion                0.0     MyModule PesterMock_e4fb0f70-3315-4be8-99b2-0856f4ce01b1
      Alias Microsoft.PowerShell.Utility\Write-Host 0.0     MyModule PesterMock_c9484003-10dc-469d-bcbb-d008c01407e1
      Alias Write-Host                              0.0     MyModule PesterMock_c9484003-10dc-469d-bcbb-d008c01407e1
      Alias Build                                   0.0     MyModule PesterMock_53a4c1dd-294b-4432-8dc9-1127d7591bcb
      Alias MyModule\Build                          0.0     MyModule PesterMock_53a4c1dd-294b-4432-8dc9-1127d7591bcb

# Verify no mocks in PS session
PS /workspaces/Pester> Get-Command PesterMock_*

PS /workspaces/Pester> Get-Alias "*Get-Version","*Get-NextVersion","*Write-Host","*Build" | Ft CommandType, Name, Version, Source, ResolvedCommandName                   

```

**Comment by nohwnd** [comment] 2020-09-29 09:35
@fflaten it might be that, we've seen mocks being left behind after the previous run was cancelled. I don't think I was inspecting all the loaded modules for mocks and removing them at the start of the run. That would probably solve the problem.

**Comment by fflaten** [comment] 2020-09-29 09:50
Yeah, could consider checking loaded modules for mocks in their module scope as well during startup of Invoke-Pester, but that's a nice to have-workaround and not the root issue.  The sample above isn't cancelled, but still fails to remove them. Shouldn't that be done as part of a *end plugin-step like the diag-output says?

Maybe I should move this into a new issue to keep this doc-related issue clean? This doc-issue is solved when the updated sample above is written in a recommended way (bug or not) and is published 🙂

**Comment by nohwnd** [comment] 2020-09-29 09:59
Then I need to investigate this further, because this clean up should work, and I don't remember touching that code recently.

**Comment by nohwnd** [comment] 2020-10-23 12:34
The issue is that the removal script runs in the caller scope, not in the module scope, trying to fix it, hopefully I won't need to introduce yet another session state property to keep track of.

**Comment by nohwnd** [comment] 2020-10-23 13:18
#1725 should fix the functionality. The docs still need update.

**Comment by fflaten** [comment] 2020-10-23 17:19
Great job! Works as expected now.
I've attempted to update the docs in pester/docs#64. Please have a look (both of you) too see if it feels better.

**Comment by nohwnd** [comment] 2020-10-24 12:47
Merged, great job thanks :)

**Closed** 2020-10-24 12:47 UTC
Labels: Documentation
