### ISSUE TITLE
Bug: Assert-MockCalled not working from Azure VSTS

### ISSUE THREAD

**Issue by vojtech-kasny** [pester/Pester#1638] opened 2020-07-27 12:59 UTC
Pester version: 5.0.2
Called test:
``` powershell
Mock -CommandName Log-Debug {Write-Host ("Switching to CI") -ForegroundColor Cyan}
(Set-BuildRunToCI).SwitchToCI | Should -BeOfType [bool]
Assert-MockCalled -CommandName Log-Debug -Times 1
```
Local run result: 
``` powershell
Describing 'Set-BuildRunToCI' Unit Tests
[+] Command was found 6ms (4ms|1ms)
  Switching to CI
[+] Call property 'SwitchToCI' should return bool
```
Azure VSTS run result:
``` powershell
Describing 'Set-BuildRunToCI' Unit Tests
[+] Command was found 4ms (3ms|1ms)
  Switching to CI. Reason:
[-] Call property 'SwitchToCI' should return bool 256ms (253ms|2ms)
  Expected Log-Debug to be called at least 1 times but was called 0 times
  at Should -Invoke @__params__p,   C:\Users\svc_devops\Documents\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1:11655
```

The message "Switching to CI" is attached by Log-Debug command, which is being called. Also from VSTS run, the function Log-Debug is not mocked at all, instead of this, it still uses default function message

``` powershell
function Set-BuildRunToCI {
    param (
        [string]$Message,
        $ShouldReturn = $false
    )
    Log-Debug "Switching to CI. Reason: $Message"
    New-Object psobject -Property @{
        SwitchToCI = $true
        ShouldReturn = $ShouldReturn
    }
}
```

**Comment by asears** [comment] 2020-07-28 02:03
I was able to run this both locally and in Azure Devops in a Powershell Script task with Advanced - Powershell Core checked.

```powershell

Describe "the test describe"{
    BeforeAll{
        Function Set-BuildRunToCI {
            Param (
                [String]$Message,
                $ShouldReturn = $false
            )
            Log-Debug "Switching to CI. Reason: $Message"
            New-Object psobject -Property @{
                SwitchToCI = $true
                ShouldReturn = $ShouldReturn
            }
        }
        Function Log-Debug (){}
        Mock "Log-Debug" -MockWith { Write-Output "Switching to CI" -ForegroundColor Cyan }
    }
    It "it should be bool"{
        (Set-BuildRunToCI).SwitchToCI | Should -BeOfType [bool]
    }
    It "it should mock Log-Debug"{
        (Set-BuildRunToCI).SwitchToCI 
        Should -Invoke Log-Debug -Times 1
    }
}
```

I did notice that creating Mock.Tests.ps1 results in below error due to the filename having mock in it, and didn't see a way to pass in a here-string as a test without similar error.

```powershell
System.Management.Automation.RuntimeException: Test cannot be directly in the root.
at New-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 871
at It, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 8262
at <ScriptBlock>, D:\projects\powershell\vsts\tests\mock.tests.ps1: line 6
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2724
at Invoke-File, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2733
at Invoke-BlockContainer, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2662
at Discover-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 1289
at Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2195
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 4201
at <ScriptBlock>, D:\projects\powershell\vsts\tests\mocking.tests.ps1: line 25
at <ScriptBlock>, <No file>: line 1
```

**Comment by vojtech-kasny** [comment] 2020-08-11 12:47
@asears 
Thanks for reply Andrew, but this does not fix the issue for me.
The problem is that locally, using Invoke-Pester command, the tests are succesful.
But when called from Azure DevOps, the mock is failing. 
I also tried to change the test as follows:
```powershell
Describe "'Set-BuildRunToCI' Unit Tests" -Tag "Function" {
    BeforeAll {
        Mock -CommandName "Log-Debug" -MockWith { Write-Output "Switching to CI" -ForegroundColor Cyan }
    }
    It "Should mock Log-Debug"{
        (Set-BuildRunToCI).SwitchToCI | Should -BeOfType [bool]
        Assert-MockCalled -CommandName Log-Debug -Times 1
    }
}
```

result 
```
Describing 'Set-BuildRunToCI' Unit Tests
  [+] Should mock Log-Debug 20ms (18ms|2ms)
```

But still fails from Azure DevOps
```
[-] 'Set-BuildRunToCI' Unit Tests.Should mock Log-Debug
 101ms (97ms|4ms)


 Expected Log-Debug to be called at least 1 times but was called 0 times
 at Should -Invoke @__params__p, C:\Users\svc_devops\Documents\WindowsPowerShell\Modules\Pester\5.0.3\Pester.psm1:11659
```

To me it looks like scope issue

**Comment by asears** [comment] 2020-08-11 13:09
That's interesting, it worked for me from Azure Devops with Powershell core option checked.  

Latest version of Pester just released addresses some scoping issues with BeforeAll, perhaps it will help.  
Did you try to mock within the It scope to confirm it's a scoping issue with BeforeAll?

Newer syntax is this format:

```powershell
Should -Invoke Log-Debug -Times 1
```

**Comment by fflaten** [comment] 2020-10-14 20:20
Can't reproduce. Works as intended locally and in Azure Devops using Pester 5.0.3 on Windows runner (same as your last run). However I did notice that you're running a self-hosted runner. Could you please:

1. Try using a cloud runner (`vmImage: 'windows-latest'`) if possible?
2. Provide the pipeline yaml-code, specifically for the test-step? I've tested with:
```
- powershell: |
    Install-Module Pester -MinimumVersion 5.0.3 -MaximumVersion 5.0.3 -Scope CurrentUser -Force
    Import-Module Pester -MaximumVersion 5.0.3
    Invoke-Pester demo.tests.ps1
  displayName: 'Powershell 1'
```
3. Try the test-file below? Your repro sample is missing the functions you mock, so we may not have been comparing the identical code.
```
Describe "'Set-BuildRunToCI' Unit Tests" -Tag "Function" {
    BeforeAll {
        Function Set-BuildRunToCI {
            Param (
                [String]$Message,
                $ShouldReturn = $false
            )
            Log-Debug "Switching to CI. Reason: $Message"
            New-Object psobject -Property @{
                SwitchToCI = $true
                ShouldReturn = $ShouldReturn
            }
        }
        Function Log-Debug (){}
        Mock -CommandName "Log-Debug" -MockWith { Write-Warning "Switching to CI" }
    }
    It "Should mock Log-Debug"{
        (Set-BuildRunToCI).SwitchToCI | Should -BeOfType [bool]
        Assert-MockCalled -CommandName Log-Debug -Times 1
    }
}
```

**Comment by nohwnd** [comment] 2020-11-01 15:13
Closing, could not repro.

**Closed by nohwnd** 2020-11-01 15:13 UTC
